//// A1 vocabulary. Ids are stored with the learner's progress: never rename
//// or reuse one. Put the canonical translation first in `sv`.

import franska/lexicon.{
  type Entry, type Word, A1, Avoir, Entry, Etre, Expression, Feminine, Masculine,
  Negate, Present, Rewrite, Sentence, Verb,
}

pub fn entries() -> List(Entry) {
  [
    // Hälsningar och fraser
    phrase("bonjour", "hälsningar", ["god dag", "goddag", "hej"], ["bonjour"]),
    phrase("bonsoir", "hälsningar", ["god kväll", "godkväll"], ["bonsoir"]),
    phrase("bonne-nuit", "hälsningar", ["god natt", "godnatt"], ["bonne nuit"]),
    phrase("salut", "hälsningar", ["hej", "tjena"], ["salut", "coucou"]),
    phrase("au-revoir", "hälsningar", ["hej då", "adjö"], ["au revoir"]),
    phrase("merci", "hälsningar", ["tack"], ["merci"]),
    phrase("merci-beaucoup", "hälsningar", ["tack så mycket"], [
      "merci beaucoup",
    ]),
    phrase("s-il-vous-plait", "hälsningar", ["snälla", "var snäll"], [
      "s'il vous plaît", "s'il te plaît",
    ]),
    phrase("excusez-moi", "hälsningar", ["ursäkta", "förlåt"], [
      "excusez-moi", "excuse-moi", "pardon",
    ]),
    phrase("oui", "hälsningar", ["ja"], ["oui"]),
    phrase("non", "hälsningar", ["nej"], ["non"]),
    phrase("comment-ca-va", "hälsningar", ["hur mår du?", "hur är det?"], [
      "comment ça va ?", "ça va ?", "comment vas-tu ?", "comment allez-vous ?",
    ]),
    phrase("je-m-appelle", "hälsningar", ["jag heter"], ["je m'appelle"]),
    // Familj och människor
    noun("mere", "familj", "mère", Feminine, ["mor", "mamma"]),
    noun("pere", "familj", "père", Masculine, ["far", "pappa"]),
    noun("frere", "familj", "frère", Masculine, ["bror", "brorsa"]),
    noun("soeur", "familj", "sœur", Feminine, ["syster"]),
    noun("fils", "familj", "fils", Masculine, ["son"]),
    noun("fille", "familj", "fille", Feminine, ["dotter", "flicka", "tjej"]),
    noun("enfant", "familj", "enfant", Masculine, ["barn"]),
    noun("ami", "familj", "ami", Masculine, ["vän", "kompis"]),
    noun("homme", "familj", "homme", Masculine, ["man"]),
    noun("femme", "familj", "femme", Feminine, ["kvinna", "fru", "hustru"]),
    // Mat och dryck
    noun("pain", "mat", "pain", Masculine, ["bröd"]),
    noun("eau", "mat", "eau", Feminine, ["vatten"]),
    noun("lait", "mat", "lait", Masculine, ["mjölk"]),
    noun("fromage", "mat", "fromage", Masculine, ["ost"]),
    noun("beurre", "mat", "beurre", Masculine, ["smör"]),
    noun("oeuf", "mat", "œuf", Masculine, ["ägg"]),
    noun("viande", "mat", "viande", Feminine, ["kött"]),
    noun("poisson", "mat", "poisson", Masculine, ["fisk"]),
    noun("pomme", "mat", "pomme", Feminine, ["äpple"]),
    noun("cafe", "mat", "café", Masculine, ["kaffe", "kafé"]),
    noun("the", "mat", "thé", Masculine, ["te"]),
    noun("vin", "mat", "vin", Masculine, ["vin"]),
    // Hemmet
    noun("maison", "hemmet", "maison", Feminine, ["hus", "hem"]),
    noun("chambre", "hemmet", "chambre", Feminine, ["sovrum", "rum"]),
    noun("cuisine", "hemmet", "cuisine", Feminine, ["kök"]),
    noun("table", "hemmet", "table", Feminine, ["bord"]),
    noun("chaise", "hemmet", "chaise", Feminine, ["stol"]),
    noun("lit", "hemmet", "lit", Masculine, ["säng"]),
    noun("porte", "hemmet", "porte", Feminine, ["dörr"]),
    noun("fenetre", "hemmet", "fenêtre", Feminine, ["fönster"]),
    noun("livre", "hemmet", "livre", Masculine, ["bok"]),
    // Djur
    noun("chat", "djur", "chat", Masculine, ["katt"]),
    noun("chien", "djur", "chien", Masculine, ["hund"]),
    noun("oiseau", "djur", "oiseau", Masculine, ["fågel"]),
    noun("cheval", "djur", "cheval", Masculine, ["häst"]),
    // Staden
    noun("ville", "staden", "ville", Feminine, ["stad"]),
    noun("rue", "staden", "rue", Feminine, ["gata"]),
    noun("ecole", "staden", "école", Feminine, ["skola"]),
    noun("gare", "staden", "gare", Feminine, [
      "järnvägsstation", "tågstation", "station",
    ]),
    noun("voiture", "staden", "voiture", Feminine, ["bil"]),
    noun("magasin", "staden", "magasin", Masculine, ["affär", "butik"]),
    noun("eglise", "staden", "église", Feminine, ["kyrka"]),
    // Vanliga verb
    verb(
      "etre",
      ["vara"],
      "être",
      #("suis", "es", "est", "sommes", "êtes", "sont"),
      "été",
      Avoir,
    ),
    verb(
      "avoir",
      ["ha"],
      "avoir",
      #("ai", "as", "a", "avons", "avez", "ont"),
      "eu",
      Avoir,
    ),
    verb(
      "aller",
      ["gå", "åka", "fara"],
      "aller",
      #("vais", "vas", "va", "allons", "allez", "vont"),
      "allé",
      Etre,
    ),
    verb(
      "faire",
      ["göra"],
      "faire",
      #("fais", "fais", "fait", "faisons", "faites", "font"),
      "fait",
      Avoir,
    ),
    verb(
      "parler",
      ["tala", "prata"],
      "parler",
      #("parle", "parles", "parle", "parlons", "parlez", "parlent"),
      "parlé",
      Avoir,
    ),
    verb(
      "aimer",
      ["älska", "tycka om", "gilla"],
      "aimer",
      #("aime", "aimes", "aime", "aimons", "aimez", "aiment"),
      "aimé",
      Avoir,
    ),
    verb(
      "manger",
      ["äta"],
      "manger",
      #("mange", "manges", "mange", "mangeons", "mangez", "mangent"),
      "mangé",
      Avoir,
    ),
    verb(
      "habiter",
      ["bo"],
      "habiter",
      #("habite", "habites", "habite", "habitons", "habitez", "habitent"),
      "habité",
      Avoir,
    ),
    verb(
      "vouloir",
      ["vilja"],
      "vouloir",
      #("veux", "veux", "veut", "voulons", "voulez", "veulent"),
      "voulu",
      Avoir,
    ),
    verb(
      "pouvoir",
      ["kunna"],
      "pouvoir",
      #("peux", "peux", "peut", "pouvons", "pouvez", "peuvent"),
      "pu",
      Avoir,
    ),
    verb(
      "prendre",
      ["ta"],
      "prendre",
      #("prends", "prends", "prend", "prenons", "prenez", "prennent"),
      "pris",
      Avoir,
    ),
    verb(
      "boire",
      ["dricka"],
      "boire",
      #("bois", "bois", "boit", "buvons", "buvez", "boivent"),
      "bu",
      Avoir,
    ),
    // Kalender, frågeord, prepositioner och småord
    phrase("lundi", "kalender", ["måndag"], ["lundi", "le lundi"]),
    phrase("mardi", "kalender", ["tisdag"], ["mardi", "le mardi"]),
    phrase("mercredi", "kalender", ["onsdag"], ["mercredi", "le mercredi"]),
    phrase("jeudi", "kalender", ["torsdag"], ["jeudi", "le jeudi"]),
    phrase("vendredi", "kalender", ["fredag"], ["vendredi", "le vendredi"]),
    phrase("samedi", "kalender", ["lördag"], ["samedi", "le samedi"]),
    phrase("dimanche", "kalender", ["söndag"], ["dimanche", "le dimanche"]),
    phrase("janvier", "kalender", ["januari"], ["janvier"]),
    phrase("fevrier", "kalender", ["februari"], ["février"]),
    phrase("mars", "kalender", ["mars"], ["mars"]),
    phrase("avril", "kalender", ["april"], ["avril"]),
    phrase("mai", "kalender", ["maj"], ["mai"]),
    phrase("juin", "kalender", ["juni"], ["juin"]),
    phrase("juillet", "kalender", ["juli"], ["juillet"]),
    phrase("aout", "kalender", ["augusti"], ["août"]),
    phrase("septembre", "kalender", ["september"], ["septembre"]),
    phrase("octobre", "kalender", ["oktober"], ["octobre"]),
    phrase("novembre", "kalender", ["november"], ["novembre"]),
    phrase("decembre", "kalender", ["december"], ["décembre"]),
    phrase("qui", "frågeord", ["vem"], ["qui"]),
    phrase("quoi", "frågeord", ["vad"], ["quoi", "que"]),
    phrase("ou-question", "frågeord", ["var", "vart"], ["où"]),
    phrase("quand", "frågeord", ["när"], ["quand"]),
    phrase("comment", "frågeord", ["hur"], ["comment"]),
    phrase("pourquoi", "frågeord", ["varför"], ["pourquoi"]),
    phrase("combien", "frågeord", ["hur mycket", "hur många"], ["combien"]),
    phrase("quel", "frågeord", ["vilken", "vilket", "vilka"], [
      "quel",
      "quelle",
      "quels",
      "quelles",
    ]),
    phrase("avec", "prepositioner", ["med"], ["avec"]),
    phrase("sans", "prepositioner", ["utan"], ["sans"]),
    phrase("chez", "prepositioner", ["hos"], ["chez"]),
    phrase("dans", "prepositioner", ["i", "inuti"], ["dans"]),
    phrase("sur", "prepositioner", ["på", "ovanpå"], ["sur"]),
    phrase("sous", "prepositioner", ["under"], ["sous"]),
    phrase("devant", "prepositioner", ["framför"], ["devant"]),
    phrase("derriere", "prepositioner", ["bakom"], ["derrière"]),
    phrase("entre", "prepositioner", ["mellan"], ["entre"]),
    phrase("pour", "prepositioner", ["för"], ["pour"]),
    phrase("a-cote-de", "prepositioner", ["bredvid"], ["à côté de"]),
    phrase("pres-de", "prepositioner", ["nära"], ["près de"]),
    phrase("loin-de", "prepositioner", ["långt från"], ["loin de"]),
    phrase("avant", "prepositioner", ["före"], ["avant"]),
    phrase("apres", "prepositioner", ["efter"], ["après"]),
    phrase("et", "småord", ["och"], ["et"]),
    phrase("ou", "småord", ["eller"], ["ou"]),
    phrase("mais", "småord", ["men"], ["mais"]),
    phrase("aussi", "småord", ["också"], ["aussi"]),
    phrase("tres", "småord", ["väldigt", "mycket"], ["très"]),
    phrase("beaucoup", "småord", ["mycket"], ["beaucoup"]),
    phrase("bien", "småord", ["väl", "bra"], ["bien"]),
    phrase("ici", "småord", ["här"], ["ici"]),
    phrase("la-bas", "småord", ["där borta", "där"], ["là-bas"]),
    // Fler substantiv
    noun("printemps", "kalender", "printemps", Masculine, ["vår"]),
    noun("ete", "kalender", "été", Masculine, ["sommar"]),
    noun("automne", "kalender", "automne", Masculine, ["höst"]),
    noun("hiver", "kalender", "hiver", Masculine, ["vinter"]),
    noun("week-end", "kalender", "week-end", Masculine, ["helg"]),
    noun("sucre", "mat", "sucre", Masculine, ["socker"]),
    noun("sel", "mat", "sel", Masculine, ["salt"]),
    noun("riz", "mat", "riz", Masculine, ["ris"]),
    noun("soupe", "mat", "soupe", Feminine, ["soppa"]),
    noun("biere", "mat", "bière", Feminine, ["öl"]),
    noun("gateau", "mat", "gâteau", Masculine, ["tårta", "kaka"]),
    noun("jus", "mat", "jus", Masculine, ["juice", "saft"]),
    noun("tomate", "mat", "tomate", Feminine, ["tomat"]),
    noun("poulet", "mat", "poulet", Masculine, ["kyckling"]),
    noun("banane", "mat", "banane", Feminine, ["banan"]),
    noun("legume", "mat", "légume", Masculine, ["grönsak"]),
    noun("fruit", "mat", "fruit", Masculine, ["frukt"]),
    noun("petit-dejeuner", "mat", "petit-déjeuner", Masculine, ["frukost"]),
    noun("dejeuner", "mat", "déjeuner", Masculine, ["lunch"]),
    noun("diner", "mat", "dîner", Masculine, ["middag"]),
    noun("salon", "hemmet", "salon", Masculine, ["vardagsrum"]),
    noun("salle-de-bain", "hemmet", "salle de bain", Feminine, ["badrum"]),
    noun("jardin", "hemmet", "jardin", Masculine, ["trädgård"]),
    noun("canape", "hemmet", "canapé", Masculine, ["soffa"]),
    noun("lampe", "hemmet", "lampe", Feminine, ["lampa"]),
    noun("telephone", "hemmet", "téléphone", Masculine, ["telefon"]),
    noun("television", "hemmet", "télévision", Feminine, ["tv", "teve"]),
    noun("frigo", "hemmet", "frigo", Masculine, ["kylskåp"]),
    noun("banque", "staden", "banque", Feminine, ["bank"]),
    noun("poste", "staden", "poste", Feminine, ["post", "posten"]),
    noun("marche", "staden", "marché", Masculine, ["marknad", "torg"]),
    noun("musee", "staden", "musée", Masculine, ["museum"]),
    noun("parc", "staden", "parc", Masculine, ["park"]),
    noun("pharmacie", "staden", "pharmacie", Feminine, ["apotek"]),
    noun("hopital", "staden", "hôpital", Masculine, ["sjukhus"]),
    noun("boulangerie", "staden", "boulangerie", Feminine, ["bageri"]),
    noun("restaurant", "staden", "restaurant", Masculine, ["restaurang"]),
    noun("aeroport", "staden", "aéroport", Masculine, ["flygplats"]),
    noun("cinema", "staden", "cinéma", Masculine, ["bio", "biograf"]),
    noun("sport", "fritid", "sport", Masculine, ["sport", "idrott"]),
    noun("musique", "fritid", "musique", Feminine, ["musik"]),
    noun("film", "fritid", "film", Masculine, ["film"]),
    noun("chanson", "fritid", "chanson", Feminine, ["sång", "visa"]),
    noun("jeu", "fritid", "jeu", Masculine, ["spel", "lek"]),
    noun("fete", "fritid", "fête", Feminine, ["fest"]),
    noun("football", "fritid", "football", Masculine, ["fotboll"]),
    noun("photo", "fritid", "photo", Feminine, ["foto", "bild"]),
    noun("velo", "fritid", "vélo", Masculine, ["cykel"]),
    noun("mari", "familj", "mari", Masculine, ["make", "man"]),
    noun("tante", "familj", "tante", Feminine, ["moster", "faster"]),
    noun("oncle", "familj", "oncle", Masculine, ["morbror", "farbror"]),
    noun("grand-pere", "familj", "grand-père", Masculine, ["morfar", "farfar"]),
    noun("grand-mere", "familj", "grand-mère", Feminine, ["mormor", "farmor"]),
    noun("cousin", "familj", "cousin", Masculine, ["kusin"]),
    noun("bebe", "familj", "bébé", Masculine, ["bebis", "baby"]),
    // Fler verb
    verb(
      "jouer",
      ["spela", "leka"],
      "jouer",
      #("joue", "joues", "joue", "jouons", "jouez", "jouent"),
      "joué",
      Avoir,
    ),
    verb(
      "chercher",
      ["leta efter", "söka"],
      "chercher",
      #("cherche", "cherches", "cherche", "cherchons", "cherchez", "cherchent"),
      "cherché",
      Avoir,
    ),
    verb(
      "trouver",
      ["hitta"],
      "trouver",
      #("trouve", "trouves", "trouve", "trouvons", "trouvez", "trouvent"),
      "trouvé",
      Avoir,
    ),
    verb(
      "donner",
      ["ge"],
      "donner",
      #("donne", "donnes", "donne", "donnons", "donnez", "donnent"),
      "donné",
      Avoir,
    ),
    verb(
      "arriver",
      ["komma fram", "anlända"],
      "arriver",
      #("arrive", "arrives", "arrive", "arrivons", "arrivez", "arrivent"),
      "arrivé",
      Etre,
    ),
    verb(
      "rester",
      ["stanna"],
      "rester",
      #("reste", "restes", "reste", "restons", "restez", "restent"),
      "resté",
      Etre,
    ),
    verb(
      "commencer",
      ["börja"],
      "commencer",
      #(
        "commence",
        "commences",
        "commence",
        "commençons",
        "commencez",
        "commencent",
      ),
      "commencé",
      Avoir,
    ),
    verb(
      "fermer",
      ["stänga"],
      "fermer",
      #("ferme", "fermes", "ferme", "fermons", "fermez", "ferment"),
      "fermé",
      Avoir,
    ),
    verb(
      "ouvrir",
      ["öppna"],
      "ouvrir",
      #("ouvre", "ouvres", "ouvre", "ouvrons", "ouvrez", "ouvrent"),
      "ouvert",
      Avoir,
    ),
    verb(
      "demander",
      ["fråga", "be om"],
      "demander",
      #("demande", "demandes", "demande", "demandons", "demandez", "demandent"),
      "demandé",
      Avoir,
    ),
    verb(
      "repondre",
      ["svara"],
      "répondre",
      #("réponds", "réponds", "répond", "répondons", "répondez", "répondent"),
      "répondu",
      Avoir,
    ),
    // Reflexiva verb
    reflexive(
      "se-lever",
      ["stiga upp", "resa sig"],
      "lever",
      #("lève", "lèves", "lève", "levons", "levez", "lèvent"),
      "levé",
    ),
    reflexive(
      "s-appeler",
      ["heta"],
      "appeler",
      #("appelle", "appelles", "appelle", "appelons", "appelez", "appellent"),
      "appelé",
    ),
    reflexive(
      "se-laver",
      ["tvätta sig"],
      "laver",
      #("lave", "laves", "lave", "lavons", "lavez", "lavent"),
      "lavé",
    ),
    reflexive(
      "se-coucher",
      ["lägga sig", "gå och lägga sig"],
      "coucher",
      #("couche", "couches", "couche", "couchons", "couchez", "couchent"),
      "couché",
    ),
    reflexive(
      "s-habiller",
      ["klä på sig"],
      "habiller",
      #("habille", "habilles", "habille", "habillons", "habillez", "habillent"),
      "habillé",
    ),
    reflexive(
      "se-reveiller",
      ["vakna"],
      "réveiller",
      #(
        "réveille",
        "réveilles",
        "réveille",
        "réveillons",
        "réveillez",
        "réveillent",
      ),
      "réveillé",
    ),
    // Adjektiv
    adjective("grand", "egenskaper", ["stor"], "grand", "grande"),
    adjective("petit", "egenskaper", ["liten"], "petit", "petite"),
    adjective("bon", "egenskaper", ["bra", "god"], "bon", "bonne"),
    adjective("mauvais", "egenskaper", ["dålig"], "mauvais", "mauvaise"),
    adjective("beau", "egenskaper", ["vacker", "snygg", "fin"], "beau", "belle"),
    adjective("joli", "egenskaper", ["söt", "fin", "vacker"], "joli", "jolie"),
    adjective("nouveau", "egenskaper", ["ny"], "nouveau", "nouvelle"),
    adjective("vieux", "egenskaper", ["gammal"], "vieux", "vieille"),
    adjective("jeune", "egenskaper", ["ung"], "jeune", "jeune"),
    adjective("long", "egenskaper", ["lång"], "long", "longue"),
    adjective("court", "egenskaper", ["kort"], "court", "courte"),
    adjective("chaud", "egenskaper", ["varm"], "chaud", "chaude"),
    adjective("froid", "egenskaper", ["kall"], "froid", "froide"),
    adjective("cher", "egenskaper", ["dyr"], "cher", "chère"),
    adjective("facile", "egenskaper", ["lätt", "enkel"], "facile", "facile"),
    adjective("difficile", "egenskaper", ["svår"], "difficile", "difficile"),
    adjective("content", "egenskaper", ["glad", "nöjd"], "content", "contente"),
    adjective("fatigue", "egenskaper", ["trött"], "fatigué", "fatiguée"),
    adjective("gentil", "egenskaper", ["snäll"], "gentil", "gentille"),
    adjective("rouge", "färger", ["röd"], "rouge", "rouge"),
    adjective("bleu", "färger", ["blå"], "bleu", "bleue"),
    adjective("vert", "färger", ["grön"], "vert", "verte"),
    adjective("jaune", "färger", ["gul"], "jaune", "jaune"),
    adjective("noir", "färger", ["svart"], "noir", "noire"),
    adjective("blanc", "färger", ["vit"], "blanc", "blanche"),
    adjective("gris", "färger", ["grå"], "gris", "grise"),
    adjective("rose", "färger", ["rosa"], "rose", "rose"),
    invariable("marron", "färger", ["brun"], "marron"),
    invariable("orange", "färger", ["orange"], "orange"),
    // Meningar
    sentence(
      "je-suis-suedois",
      "blandat",
      "Jag är svensk.",
      "Je ___ suédois.",
      ["suis"],
      "être",
    ),
    sentence(
      "nous-habitons-a-paris",
      "blandat",
      "Vi bor i Paris.",
      "Nous ___ à Paris.",
      ["habitons"],
      "habiter",
    ),
    sentence(
      "elle-a-un-chat",
      "blandat",
      "Hon har en katt.",
      "Elle ___ un chat.",
      ["a"],
      "avoir",
    ),
    sentence(
      "tu-veux-du-cafe",
      "blandat",
      "Vill du ha kaffe?",
      "Tu ___ du café ?",
      ["veux"],
      "vouloir",
    ),
    sentence(
      "ils-parlent-francais",
      "blandat",
      "De talar franska.",
      "Ils ___ français.",
      ["parlent"],
      "parler",
    ),
    sentence(
      "il-va-au-cinema",
      "blandat",
      "Han går på bio.",
      "Il ___ au cinéma.",
      ["va"],
      "aller",
    ),
    sentence(
      "vous-avez-quel-age",
      "blandat",
      "Hur gammal är ni?",
      "Vous ___ quel âge ?",
      ["avez"],
      "avoir",
    ),
    sentence(
      "nous-mangeons-une-pizza",
      "blandat",
      "Vi äter en pizza.",
      "Nous ___ une pizza.",
      ["mangeons"],
      "manger",
    ),
    sentence(
      "elles-vont-au-restaurant",
      "blandat",
      "De går på restaurang.",
      "Elles ___ au restaurant.",
      ["vont"],
      "aller",
    ),
    sentence(
      "je-fais-mes-devoirs",
      "blandat",
      "Jag gör mina läxor.",
      "Je ___ mes devoirs.",
      ["fais"],
      "faire",
    ),
    sentence(
      "j-aime-le-pain",
      "blandat",
      "Jag tycker om bröd.",
      "J'aime ___ pain.",
      ["le"],
      "le/la",
    ),
    sentence(
      "la-maison-est-grande",
      "blandat",
      "Huset är stort.",
      "___ maison est grande.",
      ["la"],
      "le/la",
    ),
    sentence(
      "c-est-le-livre-de-paul",
      "blandat",
      "Det är Pauls bok.",
      "C'est ___ livre de Paul.",
      ["le"],
      "le/la",
    ),
    sentence(
      "et-toi",
      "blandat",
      "Jag heter Anna, och du?",
      "Je m'appelle Anna, et ___ ?",
      ["toi", "vous"],
      "",
    ),
    sentence(
      "j-ai-vingt-ans",
      "blandat",
      "Jag är tjugo år.",
      "J'ai ___ ans.",
      ["vingt"],
      "20",
    ),
    sentence(
      "il-fait-beau-aujourd-hui",
      "blandat",
      "Det är fint väder i dag.",
      "Il fait ___ aujourd'hui.",
      ["beau"],
      "",
    ),
    sentence(
      "partitiv-pain",
      "partitiv",
      "Jag äter bröd.",
      "Je mange ___ pain.",
      ["du"],
      "du/de la/des",
    ),
    sentence(
      "partitiv-fromage",
      "partitiv",
      "Vill du ha ost?",
      "Tu veux ___ fromage ?",
      ["du"],
      "du/de la/des",
    ),
    sentence(
      "partitiv-soupe",
      "partitiv",
      "Jag tar soppa.",
      "Je prends ___ soupe.",
      ["de la"],
      "du/de la/des",
    ),
    sentence(
      "partitiv-eau",
      "partitiv",
      "Hon dricker vatten.",
      "Elle boit ___eau.",
      ["de l'"],
      "du/de la/de l'/des",
    ),
    sentence(
      "partitiv-pommes",
      "partitiv",
      "Vi köper äpplen.",
      "Nous achetons ___ pommes.",
      ["des"],
      "du/de la/des",
    ),
    sentence(
      "partitiv-lait",
      "partitiv",
      "Det finns mjölk i kylskåpet.",
      "Il y a ___ lait dans le frigo.",
      ["du"],
      "du/de la/des",
    ),
    sentence(
      "partitiv-negation",
      "partitiv",
      "Jag äter inte kött.",
      "Je ne mange pas ___ viande.",
      ["de"],
      "du/de la/des/de",
    ),
    sentence(
      "possessiv-frere",
      "possessiv",
      "Det är min bror.",
      "C'est ___ frère.",
      ["mon"],
      "min",
    ),
    sentence(
      "possessiv-mere",
      "possessiv",
      "Här är min mamma.",
      "Voici ___ mère.",
      ["ma"],
      "min",
    ),
    sentence(
      "possessiv-amis",
      "possessiv",
      "Här är mina vänner.",
      "Voici ___ amis.",
      ["mes"],
      "mina",
    ),
    sentence(
      "possessiv-voiture",
      "possessiv",
      "Är det din bil?",
      "C'est ___ voiture ?",
      ["ta"],
      "din",
    ),
    sentence(
      "possessiv-ecole",
      "possessiv",
      "Jag tycker om min skola.",
      "J'aime ___ école.",
      ["mon"],
      "min",
    ),
    sentence(
      "demonstrativ-livre",
      "demonstrativ",
      "Jag tycker om den här boken.",
      "J'aime ___ livre.",
      ["ce"],
      "den här",
    ),
    sentence(
      "demonstrativ-maison",
      "demonstrativ",
      "Titta på det här huset!",
      "Regarde ___ maison !",
      ["cette"],
      "det här",
    ),
    sentence(
      "demonstrativ-homme",
      "demonstrativ",
      "Vem är den här mannen?",
      "Qui est ___ homme ?",
      ["cet"],
      "den här",
    ),
    sentence(
      "demonstrativ-fleurs",
      "demonstrativ",
      "Vill du ha de här blommorna?",
      "Tu veux ___ fleurs ?",
      ["ces"],
      "de här",
    ),
    // Negation
    negate("neg-je-parle", "Jag talar inte franska.", "Je parle français.", [
      "Je ne parle pas français.",
    ]),
    negate("neg-il-aime", "Han tycker inte om kaffe.", "Il aime le café.", [
      "Il n'aime pas le café.",
    ]),
    negate(
      "neg-nous-habitons",
      "Vi bor inte i Paris.",
      "Nous habitons à Paris.",
      ["Nous n'habitons pas à Paris."],
    ),
    negate("neg-elle-est", "Hon är inte trött.", "Elle est fatiguée.", [
      "Elle n'est pas fatiguée.",
    ]),
    negate("neg-tu-as", "Du har ingen hund.", "Tu as un chien.", [
      "Tu n'as pas de chien.",
    ]),
    negate(
      "neg-ils-mangent",
      "De äter inte kött.",
      "Ils mangent de la viande.",
      ["Ils ne mangent pas de viande."],
    ),
    negate("neg-c-est", "Det är inte svårt.", "C'est difficile.", [
      "Ce n'est pas difficile.",
    ]),
    negate("neg-je-comprends", "Jag förstår inte.", "Je comprends.", [
      "Je ne comprends pas.",
    ]),
  ]
}

fn entry(id: String, theme: String, sv: List(String), word: Word) -> Entry {
  Entry(id:, level: A1, theme:, sv:, word:)
}

fn phrase(id, theme, sv, fr) -> Entry {
  entry(id, theme, sv, Expression(fr))
}

fn noun(id, theme, fr, gender, sv) -> Entry {
  entry(id, theme, sv, lexicon.noun(fr, gender))
}

/// `forms` are the présent forms; `participle` and `auxiliary` give the
/// passé composé.
fn verb(id, sv, infinitive, forms, participle, auxiliary) -> Entry {
  let #(je, tu, il, nous, vous, ils) = forms
  entry(
    id,
    "verb",
    sv,
    Verb(
      infinitive:,
      present: Present(je:, tu:, il:, nous:, vous:, ils:),
      participle:,
      auxiliary:,
      reflexive: False,
    ),
  )
}

/// A sentence with a `___` gap, its Swedish translation, the accepted
/// answers for the gap and a hint ("" for none).
fn sentence(id, theme, sv, text, answers, hint) -> Entry {
  entry(id, theme, [sv], Sentence(text:, answers:, hint:))
}

fn adjective(id, theme, sv, masculine, feminine) -> Entry {
  entry(id, theme, sv, lexicon.adjective(masculine, feminine))
}

fn invariable(id, theme, sv, form) -> Entry {
  entry(id, theme, sv, lexicon.invariable_adjective(form))
}

/// A reflexive verb, given without its pronoun ("lever" for se lever). It
/// takes être in the passé composé.
fn reflexive(id, sv, infinitive, forms, participle) -> Entry {
  let #(je, tu, il, nous, vous, ils) = forms
  entry(
    id,
    "verb",
    sv,
    Verb(
      infinitive:,
      present: Present(je:, tu:, il:, nous:, vous:, ils:),
      participle:,
      auxiliary: Etre,
      reflexive: True,
    ),
  )
}

/// A sentence to make negative, the Swedish meaning of the negative one and
/// the accepted negative sentences.
fn negate(id, sv, source, answers) -> Entry {
  entry(id, "negation", [sv], Rewrite(task: Negate, source:, answers:))
}
