//// A1 vocabulary. Ids are stored with the learner's progress: never rename
//// or reuse one. Put the canonical translation first in `sv`.

import franska/lexicon.{
  type Entry, type Question, type Word, A1, Avoir, Entry, Etre, Expression,
  Feminine, Masculine, Negate, Present, Question, Rewrite, Sentence, Text, Verb,
}

pub fn entries() -> List(Entry) {
  [
    // Hälsningar och fraser
    phrase("bonjour", "hälsningar", ["god dag", "goddag", "hej"], ["bonjour"]),
    phrase("bonsoir", "hälsningar", ["god kväll", "godkväll"], ["bonsoir"]),
    phrase("bonne-nuit", "hälsningar", ["god natt", "godnatt"], ["bonne nuit"]),
    phrase("salut", "hälsningar", ["hej", "tjena"], ["salut", "coucou"]),
    phrase("au-revoir", "hälsningar", ["hej då", "adjö"], ["au revoir"]),
    phrase("merci", "hälsningar", ["tack"], ["merci"]),
    phrase("merci-beaucoup", "hälsningar", ["tack så mycket"], [
      "merci beaucoup",
    ]),
    phrase(
      "s-il-vous-plait",
      "hälsningar",
      ["snälla", "var snäll", "var så snäll"],
      ["s'il vous plaît", "s'il te plaît"],
    ),
    phrase("excusez-moi", "hälsningar", ["ursäkta", "ursäkta mig", "förlåt"], [
      "excusez-moi", "excuse-moi", "pardon",
    ]),
    phrase("oui", "hälsningar", ["ja"], ["oui"]),
    phrase("non", "hälsningar", ["nej"], ["non"]),
    phrase("comment-ca-va", "hälsningar", ["hur mår du?", "hur är det?"], [
      "comment ça va ?", "ça va ?", "comment vas-tu ?", "comment allez-vous ?",
    ]),
    phrase("je-m-appelle", "hälsningar", ["jag heter"], ["je m'appelle"]),
    // Familj och människor
    noun("mere", "familj", "mère", Feminine, ["mor", "mamma"]),
    noun("pere", "familj", "père", Masculine, ["far", "pappa"]),
    noun("frere", "familj", "frère", Masculine, ["bror", "brorsa"]),
    noun("soeur", "familj", "sœur", Feminine, ["syster"]),
    noun("fils", "familj", "fils", Masculine, ["son"]),
    noun("fille", "familj", "fille", Feminine, ["dotter", "flicka", "tjej"]),
    noun("enfant", "familj", "enfant", Masculine, ["barn"]),
    noun("ami", "familj", "ami", Masculine, ["vän", "kompis"]),
    noun("homme", "familj", "homme", Masculine, ["man"]),
    noun("femme", "familj", "femme", Feminine, ["kvinna", "fru", "hustru"]),
    // Mat och dryck
    noun("pain", "mat", "pain", Masculine, ["bröd"]),
    noun("eau", "mat", "eau", Feminine, ["vatten"]),
    noun("lait", "mat", "lait", Masculine, ["mjölk"]),
    noun("fromage", "mat", "fromage", Masculine, ["ost"]),
    noun("beurre", "mat", "beurre", Masculine, ["smör"]),
    noun("oeuf", "mat", "œuf", Masculine, ["ägg"]),
    noun("viande", "mat", "viande", Feminine, ["kött"]),
    noun("poisson", "mat", "poisson", Masculine, ["fisk"]),
    noun("pomme", "mat", "pomme", Feminine, ["äpple"]),
    noun("cafe", "mat", "café", Masculine, ["kaffe", "kafé"]),
    noun("the", "mat", "thé", Masculine, ["te"]),
    noun("vin", "mat", "vin", Masculine, ["vin"]),
    // Hemmet
    noun("maison", "hemmet", "maison", Feminine, ["hus", "hem"]),
    noun("chambre", "hemmet", "chambre", Feminine, ["sovrum", "rum"]),
    noun("cuisine", "hemmet", "cuisine", Feminine, ["kök"]),
    noun("table", "hemmet", "table", Feminine, ["bord"]),
    noun("chaise", "hemmet", "chaise", Feminine, ["stol"]),
    noun("lit", "hemmet", "lit", Masculine, ["säng"]),
    noun("porte", "hemmet", "porte", Feminine, ["dörr"]),
    noun("fenetre", "hemmet", "fenêtre", Feminine, ["fönster"]),
    noun("livre", "hemmet", "livre", Masculine, ["bok"]),
    // Djur
    noun("chat", "djur", "chat", Masculine, ["katt"]),
    noun("chien", "djur", "chien", Masculine, ["hund"]),
    noun("oiseau", "djur", "oiseau", Masculine, ["fågel"]),
    noun("cheval", "djur", "cheval", Masculine, ["häst"]),
    // Staden
    noun("ville", "staden", "ville", Feminine, ["stad"]),
    noun("rue", "staden", "rue", Feminine, ["gata"]),
    noun("ecole", "staden", "école", Feminine, ["skola"]),
    noun("gare", "staden", "gare", Feminine, [
      "järnvägsstation", "tågstation", "station",
    ]),
    noun("voiture", "staden", "voiture", Feminine, ["bil"]),
    noun("magasin", "staden", "magasin", Masculine, ["affär", "butik"]),
    noun("eglise", "staden", "église", Feminine, ["kyrka"]),
    // Vanliga verb
    verb(
      "etre",
      ["vara"],
      "être",
      #("suis", "es", "est", "sommes", "êtes", "sont"),
      "été",
      Avoir,
    ),
    verb(
      "avoir",
      ["ha"],
      "avoir",
      #("ai", "as", "a", "avons", "avez", "ont"),
      "eu",
      Avoir,
    ),
    verb(
      "aller",
      ["gå", "åka", "fara"],
      "aller",
      #("vais", "vas", "va", "allons", "allez", "vont"),
      "allé",
      Etre,
    ),
    verb(
      "faire",
      ["göra"],
      "faire",
      #("fais", "fais", "fait", "faisons", "faites", "font"),
      "fait",
      Avoir,
    ),
    verb(
      "parler",
      ["tala", "prata"],
      "parler",
      #("parle", "parles", "parle", "parlons", "parlez", "parlent"),
      "parlé",
      Avoir,
    ),
    verb(
      "aimer",
      ["älska", "tycka om", "gilla"],
      "aimer",
      #("aime", "aimes", "aime", "aimons", "aimez", "aiment"),
      "aimé",
      Avoir,
    ),
    verb(
      "manger",
      ["äta"],
      "manger",
      #("mange", "manges", "mange", "mangeons", "mangez", "mangent"),
      "mangé",
      Avoir,
    ),
    verb(
      "habiter",
      ["bo"],
      "habiter",
      #("habite", "habites", "habite", "habitons", "habitez", "habitent"),
      "habité",
      Avoir,
    ),
    verb(
      "vouloir",
      ["vilja"],
      "vouloir",
      #("veux", "veux", "veut", "voulons", "voulez", "veulent"),
      "voulu",
      Avoir,
    ),
    verb(
      "pouvoir",
      ["kunna"],
      "pouvoir",
      #("peux", "peux", "peut", "pouvons", "pouvez", "peuvent"),
      "pu",
      Avoir,
    ),
    verb(
      "prendre",
      ["ta"],
      "prendre",
      #("prends", "prends", "prend", "prenons", "prenez", "prennent"),
      "pris",
      Avoir,
    ),
    verb(
      "boire",
      ["dricka"],
      "boire",
      #("bois", "bois", "boit", "buvons", "buvez", "boivent"),
      "bu",
      Avoir,
    ),
    // Kalender, frågeord, prepositioner och småord
    phrase("lundi", "kalender", ["måndag"], ["lundi", "le lundi"]),
    phrase("mardi", "kalender", ["tisdag"], ["mardi", "le mardi"]),
    phrase("mercredi", "kalender", ["onsdag"], ["mercredi", "le mercredi"]),
    phrase("jeudi", "kalender", ["torsdag"], ["jeudi", "le jeudi"]),
    phrase("vendredi", "kalender", ["fredag"], ["vendredi", "le vendredi"]),
    phrase("samedi", "kalender", ["lördag"], ["samedi", "le samedi"]),
    phrase("dimanche", "kalender", ["söndag"], ["dimanche", "le dimanche"]),
    phrase("janvier", "kalender", ["januari"], ["janvier"]),
    phrase("fevrier", "kalender", ["februari"], ["février"]),
    phrase("mars", "kalender", ["mars"], ["mars"]),
    phrase("avril", "kalender", ["april"], ["avril"]),
    phrase("mai", "kalender", ["maj"], ["mai"]),
    phrase("juin", "kalender", ["juni"], ["juin"]),
    phrase("juillet", "kalender", ["juli"], ["juillet"]),
    phrase("aout", "kalender", ["augusti"], ["août"]),
    phrase("septembre", "kalender", ["september"], ["septembre"]),
    phrase("octobre", "kalender", ["oktober"], ["octobre"]),
    phrase("novembre", "kalender", ["november"], ["novembre"]),
    phrase("decembre", "kalender", ["december"], ["décembre"]),
    phrase("qui", "frågeord", ["vem"], ["qui"]),
    phrase("quoi", "frågeord", ["vad"], ["quoi", "que"]),
    phrase("ou-question", "frågeord", ["var", "vart"], ["où"]),
    phrase("quand", "frågeord", ["när"], ["quand"]),
    phrase("comment", "frågeord", ["hur"], ["comment"]),
    phrase("pourquoi", "frågeord", ["varför"], ["pourquoi"]),
    phrase("combien", "frågeord", ["hur mycket", "hur många"], ["combien"]),
    phrase("quel", "frågeord", ["vilken", "vilket", "vilka"], [
      "quel",
      "quelle",
      "quels",
      "quelles",
    ]),
    phrase("avec", "prepositioner", ["med"], ["avec"]),
    phrase("sans", "prepositioner", ["utan"], ["sans"]),
    phrase("chez", "prepositioner", ["hos"], ["chez"]),
    phrase("dans", "prepositioner", ["i", "inuti"], ["dans"]),
    phrase("sur", "prepositioner", ["på", "ovanpå"], ["sur"]),
    phrase("sous", "prepositioner", ["under"], ["sous"]),
    phrase("devant", "prepositioner", ["framför"], ["devant"]),
    phrase("derriere", "prepositioner", ["bakom"], ["derrière"]),
    phrase("entre", "prepositioner", ["mellan"], ["entre"]),
    phrase("pour", "prepositioner", ["för"], ["pour"]),
    phrase("a-cote-de", "prepositioner", ["bredvid"], ["à côté de"]),
    phrase("pres-de", "prepositioner", ["nära"], ["près de"]),
    phrase("loin-de", "prepositioner", ["långt från"], ["loin de"]),
    phrase("avant", "prepositioner", ["före", "innan"], ["avant"]),
    phrase("apres", "prepositioner", ["efter"], ["après"]),
    phrase("et", "småord", ["och"], ["et"]),
    phrase("ou", "småord", ["eller"], ["ou"]),
    phrase("mais", "småord", ["men"], ["mais"]),
    phrase("aussi", "småord", ["också"], ["aussi"]),
    phrase("tres", "småord", ["väldigt", "mycket"], ["très"]),
    phrase("beaucoup", "småord", ["mycket"], ["beaucoup"]),
    phrase("bien", "småord", ["bra", "väl"], ["bien"]),
    phrase("ici", "småord", ["här"], ["ici"]),
    phrase("la-bas", "småord", ["där borta", "där"], ["là-bas"]),
    // Fler substantiv
    noun("printemps", "kalender", "printemps", Masculine, ["vår"]),
    noun("ete", "kalender", "été", Masculine, ["sommar"]),
    noun("automne", "kalender", "automne", Masculine, ["höst"]),
    noun("hiver", "kalender", "hiver", Masculine, ["vinter"]),
    noun("week-end", "kalender", "week-end", Masculine, ["helg"]),
    noun("sucre", "mat", "sucre", Masculine, ["socker"]),
    noun("sel", "mat", "sel", Masculine, ["salt"]),
    noun("riz", "mat", "riz", Masculine, ["ris"]),
    noun("soupe", "mat", "soupe", Feminine, ["soppa"]),
    noun("biere", "mat", "bière", Feminine, ["öl"]),
    noun("gateau", "mat", "gâteau", Masculine, ["tårta", "kaka"]),
    noun("jus", "mat", "jus", Masculine, ["juice", "saft"]),
    noun("tomate", "mat", "tomate", Feminine, ["tomat"]),
    noun("poulet", "mat", "poulet", Masculine, ["kyckling"]),
    noun("banane", "mat", "banane", Feminine, ["banan"]),
    noun("legume", "mat", "légume", Masculine, ["grönsak"]),
    noun("fruit", "mat", "fruit", Masculine, ["frukt"]),
    noun("petit-dejeuner", "mat", "petit-déjeuner", Masculine, ["frukost"]),
    noun("dejeuner", "mat", "déjeuner", Masculine, ["lunch"]),
    noun("diner", "mat", "dîner", Masculine, ["middag"]),
    noun("salon", "hemmet", "salon", Masculine, ["vardagsrum"]),
    noun("salle-de-bain", "hemmet", "salle de bain", Feminine, ["badrum"]),
    noun("jardin", "hemmet", "jardin", Masculine, ["trädgård"]),
    noun("canape", "hemmet", "canapé", Masculine, ["soffa"]),
    noun("lampe", "hemmet", "lampe", Feminine, ["lampa"]),
    noun("telephone", "hemmet", "téléphone", Masculine, ["telefon"]),
    noun("television", "hemmet", "télévision", Feminine, ["tv", "teve"]),
    noun("frigo", "hemmet", "frigo", Masculine, ["kylskåp"]),
    noun("banque", "staden", "banque", Feminine, ["bank"]),
    noun("poste", "staden", "poste", Feminine, ["post", "posten"]),
    noun("marche", "staden", "marché", Masculine, ["marknad", "torg"]),
    noun("musee", "staden", "musée", Masculine, ["museum"]),
    noun("parc", "staden", "parc", Masculine, ["park"]),
    noun("pharmacie", "staden", "pharmacie", Feminine, ["apotek"]),
    noun("hopital", "staden", "hôpital", Masculine, ["sjukhus"]),
    noun("boulangerie", "staden", "boulangerie", Feminine, ["bageri"]),
    noun("restaurant", "staden", "restaurant", Masculine, ["restaurang"]),
    noun("aeroport", "staden", "aéroport", Masculine, ["flygplats"]),
    noun("cinema", "staden", "cinéma", Masculine, ["bio", "biograf"]),
    noun("sport", "fritid", "sport", Masculine, ["sport", "idrott"]),
    noun("musique", "fritid", "musique", Feminine, ["musik"]),
    noun("film", "fritid", "film", Masculine, ["film"]),
    noun("chanson", "fritid", "chanson", Feminine, ["sång", "visa"]),
    noun("jeu", "fritid", "jeu", Masculine, ["spel", "lek"]),
    noun("fete", "fritid", "fête", Feminine, ["fest"]),
    noun("football", "fritid", "football", Masculine, ["fotboll"]),
    noun("photo", "fritid", "photo", Feminine, ["foto", "bild"]),
    noun("velo", "fritid", "vélo", Masculine, ["cykel"]),
    noun("mari", "familj", "mari", Masculine, ["make", "man"]),
    noun("tante", "familj", "tante", Feminine, ["moster", "faster"]),
    noun("oncle", "familj", "oncle", Masculine, ["morbror", "farbror"]),
    noun("grand-pere", "familj", "grand-père", Masculine, ["morfar", "farfar"]),
    noun("grand-mere", "familj", "grand-mère", Feminine, ["mormor", "farmor"]),
    noun("cousin", "familj", "cousin", Masculine, ["kusin"]),
    noun("bebe", "familj", "bébé", Masculine, ["bebis", "baby"]),
    // Fler verb
    verb(
      "jouer",
      ["spela", "leka"],
      "jouer",
      #("joue", "joues", "joue", "jouons", "jouez", "jouent"),
      "joué",
      Avoir,
    ),
    verb(
      "chercher",
      ["leta efter", "söka"],
      "chercher",
      #("cherche", "cherches", "cherche", "cherchons", "cherchez", "cherchent"),
      "cherché",
      Avoir,
    ),
    verb(
      "trouver",
      ["hitta"],
      "trouver",
      #("trouve", "trouves", "trouve", "trouvons", "trouvez", "trouvent"),
      "trouvé",
      Avoir,
    ),
    verb(
      "donner",
      ["ge"],
      "donner",
      #("donne", "donnes", "donne", "donnons", "donnez", "donnent"),
      "donné",
      Avoir,
    ),
    verb(
      "arriver",
      ["komma fram", "anlända"],
      "arriver",
      #("arrive", "arrives", "arrive", "arrivons", "arrivez", "arrivent"),
      "arrivé",
      Etre,
    ),
    verb(
      "rester",
      ["stanna"],
      "rester",
      #("reste", "restes", "reste", "restons", "restez", "restent"),
      "resté",
      Etre,
    ),
    verb(
      "commencer",
      ["börja"],
      "commencer",
      #(
        "commence",
        "commences",
        "commence",
        "commençons",
        "commencez",
        "commencent",
      ),
      "commencé",
      Avoir,
    ),
    verb(
      "fermer",
      ["stänga"],
      "fermer",
      #("ferme", "fermes", "ferme", "fermons", "fermez", "ferment"),
      "fermé",
      Avoir,
    ),
    verb(
      "ouvrir",
      ["öppna"],
      "ouvrir",
      #("ouvre", "ouvres", "ouvre", "ouvrons", "ouvrez", "ouvrent"),
      "ouvert",
      Avoir,
    ),
    verb(
      "demander",
      ["fråga", "be om"],
      "demander",
      #("demande", "demandes", "demande", "demandons", "demandez", "demandent"),
      "demandé",
      Avoir,
    ),
    verb(
      "repondre",
      ["svara"],
      "répondre",
      #("réponds", "réponds", "répond", "répondons", "répondez", "répondent"),
      "répondu",
      Avoir,
    ),
    // Reflexiva verb
    reflexive(
      "se-lever",
      ["stiga upp", "gå upp", "resa sig"],
      "lever",
      #("lève", "lèves", "lève", "levons", "levez", "lèvent"),
      "levé",
    ),
    reflexive(
      "s-appeler",
      ["heta"],
      "appeler",
      #("appelle", "appelles", "appelle", "appelons", "appelez", "appellent"),
      "appelé",
    ),
    reflexive(
      "se-laver",
      ["tvätta sig"],
      "laver",
      #("lave", "laves", "lave", "lavons", "lavez", "lavent"),
      "lavé",
    ),
    reflexive(
      "se-coucher",
      ["lägga sig", "gå och lägga sig"],
      "coucher",
      #("couche", "couches", "couche", "couchons", "couchez", "couchent"),
      "couché",
    ),
    reflexive(
      "s-habiller",
      ["klä på sig"],
      "habiller",
      #("habille", "habilles", "habille", "habillons", "habillez", "habillent"),
      "habillé",
    ),
    reflexive(
      "se-reveiller",
      ["vakna"],
      "réveiller",
      #(
        "réveille",
        "réveilles",
        "réveille",
        "réveillons",
        "réveillez",
        "réveillent",
      ),
      "réveillé",
    ),
    // Adjektiv
    adjective("grand", "egenskaper", ["stor"], "grand", "grande"),
    adjective("petit", "egenskaper", ["liten"], "petit", "petite"),
    adjective("bon", "egenskaper", ["god", "bra"], "bon", "bonne"),
    adjective("mauvais", "egenskaper", ["dålig"], "mauvais", "mauvaise"),
    adjective("beau", "egenskaper", ["vacker", "snygg", "fin"], "beau", "belle"),
    adjective("joli", "egenskaper", ["söt", "fin", "vacker"], "joli", "jolie"),
    adjective("nouveau", "egenskaper", ["ny"], "nouveau", "nouvelle"),
    adjective("vieux", "egenskaper", ["gammal"], "vieux", "vieille"),
    adjective("jeune", "egenskaper", ["ung"], "jeune", "jeune"),
    adjective("long", "egenskaper", ["lång"], "long", "longue"),
    adjective("court", "egenskaper", ["kort"], "court", "courte"),
    adjective("chaud", "egenskaper", ["varm"], "chaud", "chaude"),
    adjective("froid", "egenskaper", ["kall"], "froid", "froide"),
    adjective("cher", "egenskaper", ["dyr"], "cher", "chère"),
    adjective("facile", "egenskaper", ["lätt", "enkel"], "facile", "facile"),
    adjective("difficile", "egenskaper", ["svår"], "difficile", "difficile"),
    adjective("content", "egenskaper", ["glad", "nöjd"], "content", "contente"),
    adjective("fatigue", "egenskaper", ["trött"], "fatigué", "fatiguée"),
    adjective("gentil", "egenskaper", ["snäll"], "gentil", "gentille"),
    adjective("rouge", "färger", ["röd"], "rouge", "rouge"),
    adjective("bleu", "färger", ["blå"], "bleu", "bleue"),
    adjective("vert", "färger", ["grön"], "vert", "verte"),
    adjective("jaune", "färger", ["gul"], "jaune", "jaune"),
    adjective("noir", "färger", ["svart"], "noir", "noire"),
    adjective("blanc", "färger", ["vit"], "blanc", "blanche"),
    adjective("gris", "färger", ["grå"], "gris", "grise"),
    adjective("rose", "färger", ["rosa"], "rose", "rose"),
    invariable("marron", "färger", ["brun"], "marron"),
    invariable("orange", "färger", ["orange"], "orange"),
    // Mer vardagsvokabulär (A1)
    noun("lapin", "djur", "lapin", Masculine, ["kanin"]),
    noun("vache", "djur", "vache", Feminine, ["ko"]),
    noun("cochon", "djur", "cochon", Masculine, ["gris"]),
    noun("mouton", "djur", "mouton", Masculine, ["får"]),
    noun("souris", "djur", "souris", Feminine, ["mus"]),
    noun("ours", "djur", "ours", Masculine, ["björn"]),
    noun("lion", "djur", "lion", Masculine, ["lejon"]),
    noun("loup", "djur", "loup", Masculine, ["varg"]),
    noun("canard", "djur", "canard", Masculine, ["anka"]),
    noun("poule", "djur", "poule", Feminine, ["höna"]),
    noun("serpent", "djur", "serpent", Masculine, ["orm"]),
    noun("elephant", "djur", "éléphant", Masculine, ["elefant"]),
    noun("singe", "djur", "singe", Masculine, ["apa"]),
    noun("carotte", "mat", "carotte", Feminine, ["morot"]),
    noun("pomme-de-terre", "mat", "pomme de terre", Feminine, ["potatis"]),
    noun("oignon", "mat", "oignon", Masculine, ["lök"]),
    noun("salade", "mat", "salade", Feminine, ["sallad"]),
    noun("confiture", "mat", "confiture", Feminine, ["sylt"]),
    noun("chocolat", "mat", "chocolat", Masculine, ["choklad"]),
    noun("glace", "mat", "glace", Feminine, ["glass"]),
    noun("orange-fruit", "mat", "orange", Feminine, ["apelsin"]),
    noun("fraise", "mat", "fraise", Feminine, ["jordgubbe"]),
    noun("citron", "mat", "citron", Masculine, ["citron"]),
    noun("jambon", "mat", "jambon", Masculine, ["skinka"]),
    noun("saucisse", "mat", "saucisse", Feminine, ["korv"]),
    noun("pizza", "mat", "pizza", Feminine, ["pizza"]),
    noun("sandwich", "mat", "sandwich", Masculine, ["smörgås"]),
    noun("yaourt", "mat", "yaourt", Masculine, ["yoghurt"]),
    noun("crepe", "mat", "crêpe", Feminine, ["pannkaka"]),
    noun("croissant", "mat", "croissant", Masculine, ["croissant"]),
    noun("baguette", "mat", "baguette", Feminine, ["baguette"]),
    noun("bouteille", "mat", "bouteille", Feminine, ["flaska"]),
    noun("verre", "mat", "verre", Masculine, ["glas"]),
    noun("tasse", "mat", "tasse", Feminine, ["kopp"]),
    noun("assiette", "mat", "assiette", Feminine, ["tallrik"]),
    noun("couteau", "mat", "couteau", Masculine, ["kniv"]),
    noun("fourchette", "mat", "fourchette", Feminine, ["gaffel"]),
    noun("cuillere", "mat", "cuillère", Feminine, ["sked"]),
    phrase("pates", "mat", ["pasta"], ["les pâtes"]),
    noun("appartement", "hemmet", "appartement", Masculine, ["lägenhet"]),
    noun("escalier", "hemmet", "escalier", Masculine, ["trappa"]),
    noun("mur", "hemmet", "mur", Masculine, ["vägg"]),
    noun("toit", "hemmet", "toit", Masculine, ["tak"]),
    noun("sol", "hemmet", "sol", Masculine, ["golv"]),
    noun("armoire", "hemmet", "armoire", Feminine, ["garderob"]),
    noun("miroir", "hemmet", "miroir", Masculine, ["spegel"]),
    noun("douche", "hemmet", "douche", Feminine, ["dusch"]),
    noun("tapis", "hemmet", "tapis", Masculine, ["matta"]),
    noun("placard", "hemmet", "placard", Masculine, ["skåp"]),
    noun("radio", "hemmet", "radio", Feminine, ["radio"]),
    phrase("toilettes", "hemmet", ["toalett", "toaletten"], ["les toilettes"]),
    noun("place", "staden", "place", Feminine, ["torg", "plats"]),
    noun("pont", "staden", "pont", Masculine, ["bro"]),
    noun("bus", "staden", "bus", Masculine, ["buss"]),
    noun("metro", "staden", "métro", Masculine, ["tunnelbana"]),
    noun("taxi", "staden", "taxi", Masculine, ["taxi"]),
    noun("supermarche", "staden", "supermarché", Masculine, [
      "stormarknad",
      "mataffär",
    ]),
    noun("piscine", "staden", "piscine", Feminine, ["simhall", "badhus", "pool"]),
    noun("bibliotheque", "staden", "bibliothèque", Feminine, ["bibliotek"]),
    noun("police", "staden", "police", Feminine, ["polisen"]),
    noun("quartier", "staden", "quartier", Masculine, ["kvarter", "stadsdel"]),
    noun("centre-ville", "staden", "centre-ville", Masculine, ["centrum"]),
    noun("nez", "kroppen", "nez", Masculine, ["näsa"]),
    noun("oreille", "kroppen", "oreille", Feminine, ["öra"]),
    noun("dent", "kroppen", "dent", Feminine, ["tand"]),
    noun("ventre", "kroppen", "ventre", Masculine, ["mage"]),
    noun("doigt", "kroppen", "doigt", Masculine, ["finger"]),
    noun("genou", "kroppen", "genou", Masculine, ["knä"]),
    noun("epaule", "kroppen", "épaule", Feminine, ["axel"]),
    noun("cou", "kroppen", "cou", Masculine, ["hals"]),
    noun("visage", "kroppen", "visage", Masculine, ["ansikte"]),
    phrase("cheveux", "kroppen", ["hår", "håret"], ["les cheveux"]),
    noun("pull", "kläder", "pull", Masculine, ["tröja"]),
    noun("tee-shirt", "kläder", "tee-shirt", Masculine, ["t-shirt"]),
    noun("jean", "kläder", "jean", Masculine, ["jeans"]),
    noun("chaussette", "kläder", "chaussette", Feminine, ["strumpa"]),
    noun("casquette", "kläder", "casquette", Feminine, ["keps"]),
    noun("echarpe", "kläder", "écharpe", Feminine, ["halsduk"]),
    noun("sac", "kläder", "sac", Masculine, ["väska"]),
    noun("ceinture", "kläder", "ceinture", Feminine, ["bälte"]),
    noun("maillot-de-bain", "kläder", "maillot de bain", Masculine, ["baddräkt"]),
    phrase("lunettes", "kläder", ["glasögon"], ["les lunettes"]),
    noun("garcon", "familj", "garçon", Masculine, ["pojke"]),
    noun("voisin", "familj", "voisin", Masculine, ["granne"]),
    noun("famille", "familj", "famille", Feminine, ["familj"]),
    noun("prenom", "familj", "prénom", Masculine, ["förnamn"]),
    noun("nom", "familj", "nom", Masculine, ["namn"]),
    noun("adresse", "familj", "adresse", Feminine, ["adress"]),
    noun("age", "familj", "âge", Masculine, ["ålder"]),
    noun("dame", "familj", "dame", Feminine, ["dam"]),
    noun("monsieur", "familj", "monsieur", Masculine, ["herre"]),
    phrase("parents", "familj", ["föräldrar", "föräldrarna"], ["les parents"]),
    noun("classe", "skolan", "classe", Feminine, ["klass"]),
    noun("eleve", "skolan", "élève", Masculine, ["elev"]),
    noun("cahier", "skolan", "cahier", Masculine, ["skrivbok", "häfte"]),
    noun("stylo", "skolan", "stylo", Masculine, ["penna"]),
    noun("crayon", "skolan", "crayon", Masculine, ["blyertspenna"]),
    noun("lecon", "skolan", "leçon", Feminine, ["lektion"]),
    noun("reponse", "skolan", "réponse", Feminine, ["svar"]),
    noun("mot", "skolan", "mot", Masculine, ["ord"]),
    noun("phrase", "skolan", "phrase", Feminine, ["mening"]),
    noun("tableau", "skolan", "tableau", Masculine, ["tavla"]),
    noun("examen", "skolan", "examen", Masculine, ["prov", "examen"]),
    noun("langue", "skolan", "langue", Feminine, ["språk", "tunga"]),
    noun("universite", "skolan", "université", Feminine, ["universitet"]),
    noun("etudiant", "skolan", "étudiant", Masculine, ["student"]),
    noun("piano", "fritid", "piano", Masculine, ["piano"]),
    noun("guitare", "fritid", "guitare", Feminine, ["gitarr"]),
    noun("dessin", "fritid", "dessin", Masculine, ["teckning"]),
    noun("peinture", "fritid", "peinture", Feminine, ["målning"]),
    noun("tennis", "fritid", "tennis", Masculine, ["tennis"]),
    noun("natation", "fritid", "natation", Feminine, ["simning"]),
    noun("promenade", "fritid", "promenade", Feminine, ["promenad"]),
    noun("concert", "fritid", "concert", Masculine, ["konsert"]),
    noun("theatre", "fritid", "théâtre", Masculine, ["teater"]),
    phrase("vacances", "fritid", ["semester", "lov"], ["les vacances"]),
    noun("minute", "tid", "minute", Feminine, ["minut"]),
    noun("seconde", "tid", "seconde", Feminine, ["sekund"]),
    noun("apres-midi", "tid", "après-midi", Masculine, ["eftermiddag"]),
    noun("nuit", "tid", "nuit", Feminine, ["natt"]),
    noun("date", "tid", "date", Feminine, ["datum"]),
    phrase("midi", "tid", ["mitt på dagen", "klockan tolv"], ["midi"]),
    phrase("minuit", "tid", ["midnatt"], ["minuit"]),
    phrase("bientot", "tid", ["snart"], ["bientôt"]),
    phrase("tard", "tid", ["sent"], ["tard"]),
    phrase("tot", "tid", ["tidigt"], ["tôt"]),
    phrase("deja", "tid", ["redan"], ["déjà"]),
    phrase("encore", "tid", ["igen", "fortfarande"], ["encore"]),
    phrase("ensuite", "tid", ["sedan", "därefter"], ["ensuite", "puis"]),
    phrase("parfois", "tid", ["ibland"], ["parfois", "quelquefois"]),
    phrase("jamais", "tid", ["aldrig"], ["jamais"]),
    phrase("peut-etre", "småord", ["kanske"], ["peut-être"]),
    phrase("vraiment", "småord", ["verkligen"], ["vraiment"]),
    phrase("seulement", "småord", ["bara", "endast"], ["seulement"]),
    phrase("assez", "småord", ["ganska", "tillräckligt"], ["assez"]),
    phrase("trop", "småord", ["för mycket", "för"], ["trop"]),
    phrase("un-peu", "småord", ["lite"], ["un peu"]),
    phrase("ensemble", "småord", ["tillsammans"], ["ensemble"]),
    phrase("vite", "småord", ["snabbt", "fort"], ["vite"]),
    phrase("la", "småord", ["där"], ["là"]),
    phrase("si", "småord", ["om"], ["si"]),
    phrase("parce-que", "småord", ["eftersom", "för att"], ["parce que"]),
    phrase("alors", "småord", ["så", "då"], ["alors"]),
    phrase("quelque-chose", "småord", ["något"], ["quelque chose"]),
    phrase("quelqu-un", "småord", ["någon"], ["quelqu'un"]),
    phrase("tout", "småord", ["allt"], ["tout"]),
    phrase("rien", "småord", ["ingenting", "inget"], ["rien"]),
    phrase("personne", "småord", ["ingen"], ["personne"]),
    phrase("bonne-journee", "vardagsfraser", ["ha en bra dag"], [
      "bonne journée",
    ]),
    phrase("bon-week-end", "vardagsfraser", ["trevlig helg"], ["bon week-end"]),
    phrase("a-demain", "vardagsfraser", ["vi ses i morgon"], ["à demain"]),
    phrase("a-plus-tard", "vardagsfraser", ["vi ses senare"], [
      "à plus tard",
      "à plus",
    ]),
    phrase("enchante", "vardagsfraser", ["trevligt att träffas"], [
      "enchanté",
      "enchantée",
    ]),
    phrase("pas-de-probleme", "vardagsfraser", ["inga problem"], [
      "pas de problème",
    ]),
    phrase("bien-sur", "vardagsfraser", ["självklart", "såklart"], ["bien sûr"]),
    phrase("voila", "vardagsfraser", ["här är", "där är", "varsågod"], ["voilà"]),
    phrase(
      "je-suis-desole",
      "vardagsfraser",
      ["förlåt", "jag ber om ursäkt", "jag är ledsen", "förlåt mig"],
      [
        "je suis désolé",
        "je suis désolée",
        "désolé",
        "désolée",
        "pardon",
      ],
    ),
    phrase("felicitations", "vardagsfraser", ["gratulerar", "grattis"], [
      "félicitations",
    ]),
    phrase("bon-anniversaire", "vardagsfraser", ["grattis på födelsedagen"], [
      "bon anniversaire",
      "joyeux anniversaire",
    ]),
    phrase("bonne-chance", "vardagsfraser", ["lycka till"], ["bonne chance"]),
    phrase("il-y-a", "vardagsfraser", ["det finns"], ["il y a"]),
    phrase("c-est", "vardagsfraser", ["det är"], ["c'est"]),
    noun("suede", "länder", "Suède", Feminine, ["Sverige"]),
    noun("france", "länder", "France", Feminine, ["Frankrike"]),
    noun("allemagne", "länder", "Allemagne", Feminine, ["Tyskland"]),
    noun("espagne", "länder", "Espagne", Feminine, ["Spanien"]),
    noun("italie", "länder", "Italie", Feminine, ["Italien"]),
    noun("angleterre", "länder", "Angleterre", Feminine, ["England"]),
    noun("norvege", "länder", "Norvège", Feminine, ["Norge"]),
    noun("danemark", "länder", "Danemark", Masculine, ["Danmark"]),
    noun("finlande", "länder", "Finlande", Feminine, ["Finland"]),
    noun("canada", "länder", "Canada", Masculine, ["Kanada"]),
    noun("belgique", "länder", "Belgique", Feminine, ["Belgien"]),
    noun("suisse", "länder", "Suisse", Feminine, ["Schweiz"]),
    adjective("suedois", "länder", ["svensk"], "suédois", "suédoise"),
    adjective("francais", "länder", ["fransk"], "français", "française"),
    adjective("anglais", "länder", ["engelsk"], "anglais", "anglaise"),
    adjective("allemand", "länder", ["tysk"], "allemand", "allemande"),
    adjective("espagnol", "länder", ["spansk"], "espagnol", "espagnole"),
    adjective("italien", "länder", ["italiensk"], "italien", "italienne"),
    adjective("americain", "länder", ["amerikansk"], "américain", "américaine"),
    adjective("norvegien", "länder", ["norsk"], "norvégien", "norvégienne"),
    adjective("danois", "länder", ["dansk"], "danois", "danoise"),
    adjective("finlandais", "länder", ["finsk"], "finlandais", "finlandaise"),
    adjective("lourd", "egenskaper", ["tung"], "lourd", "lourde"),
    adjective("large", "egenskaper", ["bred"], "large", "large"),
    adjective("etroit", "egenskaper", ["trång", "smal"], "étroit", "étroite"),
    adjective("haut", "egenskaper", ["hög"], "haut", "haute"),
    adjective("bas", "egenskaper", ["låg"], "bas", "basse"),
    adjective("riche", "egenskaper", ["rik"], "riche", "riche"),
    adjective("pauvre", "egenskaper", ["fattig"], "pauvre", "pauvre"),
    adjective(
      "intelligent",
      "egenskaper",
      ["intelligent", "smart"],
      "intelligent",
      "intelligente",
    ),
    adjective(
      "sympathique",
      "egenskaper",
      ["sympatisk", "trevlig"],
      "sympathique",
      "sympathique",
    ),
    adjective("drole", "egenskaper", ["rolig"], "drôle", "drôle"),
    adjective(
      "interessant",
      "egenskaper",
      ["intressant"],
      "intéressant",
      "intéressante",
    ),
    adjective("ennuyeux", "egenskaper", ["tråkig"], "ennuyeux", "ennuyeuse"),
    adjective(
      "delicieux",
      "egenskaper",
      ["utsökt", "jättegod", "läcker", "god"],
      "délicieux",
      "délicieuse",
    ),
    adjective("ferme-adj", "egenskaper", ["stängd"], "fermé", "fermée"),
    adjective("ouvert", "egenskaper", ["öppen"], "ouvert", "ouverte"),
    adjective("seul", "egenskaper", ["ensam"], "seul", "seule"),
    adjective("premier", "egenskaper", ["första"], "premier", "première"),
    adjective(
      "dernier",
      "egenskaper",
      ["sista", "senaste"],
      "dernier",
      "dernière",
    ),
    adjective("prochain", "egenskaper", ["nästa"], "prochain", "prochaine"),
    adjective("meme", "egenskaper", ["samma"], "même", "même"),
    adjective("autre", "egenskaper", ["annan"], "autre", "autre"),
    adjective("faux", "egenskaper", ["fel", "falsk"], "faux", "fausse"),
    adjective("vrai", "egenskaper", ["sann"], "vrai", "vraie"),
    adjective("celebre", "egenskaper", ["känd", "berömd"], "célèbre", "célèbre"),
    adjective("calme", "egenskaper", ["lugn"], "calme", "calme"),
    adjective("sur-adj", "egenskaper", ["säker"], "sûr", "sûre"),
    verb(
      "chanter",
      ["sjunga"],
      "chanter",
      #("chante", "chantes", "chante", "chantons", "chantez", "chantent"),
      "chanté",
      Avoir,
    ),
    verb(
      "danser",
      ["dansa"],
      "danser",
      #("danse", "danses", "danse", "dansons", "dansez", "dansent"),
      "dansé",
      Avoir,
    ),
    verb(
      "nager",
      ["simma"],
      "nager",
      #("nage", "nages", "nage", "nageons", "nagez", "nagent"),
      "nagé",
      Avoir,
    ),
    verb(
      "marcher",
      ["gå till fots", "promenera", "gå"],
      "marcher",
      #("marche", "marches", "marche", "marchons", "marchez", "marchent"),
      "marché",
      Avoir,
    ),
    verb(
      "aider",
      ["hjälpa"],
      "aider",
      #("aide", "aides", "aide", "aidons", "aidez", "aident"),
      "aidé",
      Avoir,
    ),
    verb(
      "apprendre",
      ["lära sig", "lära"],
      "apprendre",
      #(
        "apprends",
        "apprends",
        "apprend",
        "apprenons",
        "apprenez",
        "apprennent",
      ),
      "appris",
      Avoir,
    ),
    verb(
      "oublier",
      ["glömma"],
      "oublier",
      #("oublie", "oublies", "oublie", "oublions", "oubliez", "oublient"),
      "oublié",
      Avoir,
    ),
    verb(
      "penser",
      ["tänka", "tro"],
      "penser",
      #("pense", "penses", "pense", "pensons", "pensez", "pensent"),
      "pensé",
      Avoir,
    ),
    verb(
      "porter",
      ["bära", "ha på sig"],
      "porter",
      #("porte", "portes", "porte", "portons", "portez", "portent"),
      "porté",
      Avoir,
    ),
    verb(
      "cuisiner",
      ["laga mat"],
      "cuisiner",
      #("cuisine", "cuisines", "cuisine", "cuisinons", "cuisinez", "cuisinent"),
      "cuisiné",
      Avoir,
    ),
    verb(
      "telephoner",
      ["telefonera", "ringa"],
      "téléphoner",
      #(
        "téléphone",
        "téléphones",
        "téléphone",
        "téléphonons",
        "téléphonez",
        "téléphonent",
      ),
      "téléphoné",
      Avoir,
    ),
    verb(
      "visiter",
      ["besöka"],
      "visiter",
      #("visite", "visites", "visite", "visitons", "visitez", "visitent"),
      "visité",
      Avoir,
    ),
    verb(
      "entrer",
      ["gå in", "komma in"],
      "entrer",
      #("entre", "entres", "entre", "entrons", "entrez", "entrent"),
      "entré",
      Etre,
    ),
    verb(
      "monter",
      ["gå upp", "åka upp"],
      "monter",
      #("monte", "montes", "monte", "montons", "montez", "montent"),
      "monté",
      Etre,
    ),
    verb(
      "descendre",
      ["gå ner", "åka ner"],
      "descendre",
      #(
        "descends",
        "descends",
        "descend",
        "descendons",
        "descendez",
        "descendent",
      ),
      "descendu",
      Etre,
    ),
    verb(
      "tomber",
      ["falla", "ramla"],
      "tomber",
      #("tombe", "tombes", "tombe", "tombons", "tombez", "tombent"),
      "tombé",
      Etre,
    ),
    verb(
      "courir",
      ["springa"],
      "courir",
      #("cours", "cours", "court", "courons", "courez", "courent"),
      "couru",
      Avoir,
    ),
    verb(
      "croire",
      ["tro på", "tro"],
      "croire",
      #("crois", "crois", "croit", "croyons", "croyez", "croient"),
      "cru",
      Avoir,
    ),
    // Meningar
    sentence(
      "je-suis-suedois",
      "meningar",
      "Jag är svensk.",
      "Je ___ suédois.",
      ["suis"],
      "être",
    ),
    sentence(
      "nous-habitons-a-paris",
      "meningar",
      "Vi bor i Paris.",
      "Nous ___ à Paris.",
      ["habitons"],
      "habiter",
    ),
    sentence(
      "elle-a-un-chat",
      "meningar",
      "Hon har en katt.",
      "Elle ___ un chat.",
      ["a"],
      "avoir",
    ),
    sentence(
      "tu-veux-du-cafe",
      "meningar",
      "Vill du ha kaffe?",
      "Tu ___ du café ?",
      ["veux"],
      "vouloir",
    ),
    sentence(
      "ils-parlent-francais",
      "meningar",
      "De talar franska.",
      "Ils ___ français.",
      ["parlent"],
      "parler",
    ),
    sentence(
      "il-va-au-cinema",
      "meningar",
      "Han går på bio.",
      "Il ___ au cinéma.",
      ["va"],
      "aller",
    ),
    sentence(
      "vous-avez-quel-age",
      "meningar",
      "Hur gammal är ni?",
      "Vous ___ quel âge ?",
      ["avez"],
      "avoir",
    ),
    sentence(
      "nous-mangeons-une-pizza",
      "meningar",
      "Vi äter en pizza.",
      "Nous ___ une pizza.",
      ["mangeons"],
      "manger",
    ),
    sentence(
      "elles-vont-au-restaurant",
      "meningar",
      "De går på restaurang.",
      "Elles ___ au restaurant.",
      ["vont"],
      "aller",
    ),
    sentence(
      "je-fais-mes-devoirs",
      "meningar",
      "Jag gör mina läxor.",
      "Je ___ mes devoirs.",
      ["fais"],
      "faire",
    ),
    sentence(
      "j-aime-le-pain",
      "meningar",
      "Jag tycker om bröd.",
      "J'aime ___ pain.",
      ["le"],
      "le/la",
    ),
    sentence(
      "la-maison-est-grande",
      "meningar",
      "Huset är stort.",
      "___ maison est grande.",
      ["La"],
      "le/la",
    ),
    sentence(
      "c-est-le-livre-de-paul",
      "meningar",
      "Det är Pauls bok.",
      "C'est ___ livre de Paul.",
      ["le"],
      "le/la",
    ),
    sentence(
      "et-toi",
      "meningar",
      "Jag heter Anna, och du?",
      "Je m'appelle Anna, et ___ ?",
      ["toi", "vous"],
      "",
    ),
    sentence(
      "j-ai-vingt-ans",
      "meningar",
      "Jag är tjugo år.",
      "J'ai ___ ans.",
      ["vingt"],
      "20",
    ),
    sentence(
      "il-fait-beau-aujourd-hui",
      "meningar",
      "Det är fint väder i dag.",
      "Il fait ___ aujourd'hui.",
      ["beau"],
      "",
    ),
    sentence(
      "partitiv-pain",
      "partitiv",
      "Jag äter bröd.",
      "Je mange ___ pain.",
      ["du"],
      "du/de la/des",
    ),
    sentence(
      "partitiv-fromage",
      "partitiv",
      "Vill du ha ost?",
      "Tu veux ___ fromage ?",
      ["du"],
      "du/de la/des",
    ),
    sentence(
      "partitiv-soupe",
      "partitiv",
      "Jag tar soppa.",
      "Je prends ___ soupe.",
      ["de la"],
      "du/de la/des",
    ),
    sentence(
      "partitiv-eau",
      "partitiv",
      "Hon dricker vatten.",
      "Elle boit ___eau.",
      ["de l'"],
      "du/de la/de l'/des",
    ),
    sentence(
      "partitiv-pommes",
      "partitiv",
      "Vi köper äpplen.",
      "Nous achetons ___ pommes.",
      ["des"],
      "du/de la/des",
    ),
    sentence(
      "partitiv-lait",
      "partitiv",
      "Det finns mjölk i kylskåpet.",
      "Il y a ___ lait dans le frigo.",
      ["du"],
      "du/de la/des",
    ),
    sentence(
      "partitiv-negation",
      "partitiv",
      "Jag äter inte kött.",
      "Je ne mange pas ___ viande.",
      ["de"],
      "du/de la/des/de",
    ),
    sentence(
      "possessiv-frere",
      "possessiv",
      "Det är min bror.",
      "C'est ___ frère.",
      ["mon"],
      "min",
    ),
    sentence(
      "possessiv-mere",
      "possessiv",
      "Här är min mamma.",
      "Voici ___ mère.",
      ["ma"],
      "min",
    ),
    sentence(
      "possessiv-amis",
      "possessiv",
      "Här är mina vänner.",
      "Voici ___ amis.",
      ["mes"],
      "mina",
    ),
    sentence(
      "possessiv-voiture",
      "possessiv",
      "Är det din bil?",
      "C'est ___ voiture ?",
      ["ta"],
      "din",
    ),
    sentence(
      "possessiv-ecole",
      "possessiv",
      "Jag tycker om min skola.",
      "J'aime ___ école.",
      ["mon"],
      "min",
    ),
    sentence(
      "demonstrativ-livre",
      "demonstrativ",
      "Jag tycker om den här boken.",
      "J'aime ___ livre.",
      ["ce"],
      "den här",
    ),
    sentence(
      "demonstrativ-maison",
      "demonstrativ",
      "Titta på det här huset!",
      "Regarde ___ maison !",
      ["cette"],
      "det här",
    ),
    sentence(
      "demonstrativ-homme",
      "demonstrativ",
      "Vem är den här mannen?",
      "Qui est ___ homme ?",
      ["cet"],
      "den här",
    ),
    sentence(
      "demonstrativ-fleurs",
      "demonstrativ",
      "Vill du ha de här blommorna?",
      "Tu veux ___ fleurs ?",
      ["ces"],
      "de här",
    ),
    // Negation
    negate("neg-je-parle", "Jag talar inte franska.", "Je parle français.", [
      "Je ne parle pas français.",
    ]),
    negate("neg-il-aime", "Han tycker inte om kaffe.", "Il aime le café.", [
      "Il n'aime pas le café.",
    ]),
    negate(
      "neg-nous-habitons",
      "Vi bor inte i Paris.",
      "Nous habitons à Paris.",
      ["Nous n'habitons pas à Paris."],
    ),
    negate("neg-elle-est", "Hon är inte trött.", "Elle est fatiguée.", [
      "Elle n'est pas fatiguée.",
    ]),
    negate("neg-tu-as", "Du har ingen hund.", "Tu as un chien.", [
      "Tu n'as pas de chien.",
    ]),
    negate(
      "neg-ils-mangent",
      "De äter inte kött.",
      "Ils mangent de la viande.",
      ["Ils ne mangent pas de viande."],
    ),
    negate("neg-c-est", "Det är inte svårt.", "C'est difficile.", [
      "Ce n'est pas difficile.",
    ]),
    negate("neg-je-comprends", "Jag förstår inte.", "Je comprends.", [
      "Je ne comprends pas.",
    ]),
    // Texter
    text(
      "text-lea",
      "Je m'appelle Léa",
      "Bonjour ! Je m'appelle Léa. J'ai vingt-deux ans et j'habite à Lyon.\nJe suis étudiante à l'université. J'ai un frère, Tom. Il a seize ans.\nNous avons un chat noir. Le week-end, j'aime lire et jouer de la guitare.",
      "Hej! Jag heter Léa. Jag är tjugotvå år och bor i Lyon.\nJag studerar på universitetet. Jag har en bror, Tom. Han är sexton år.\nVi har en svart katt. På helgen tycker jag om att läsa och spela gitarr.",
      [
        question("Var bor Léa?", ["I Lyon", "I Paris", "I Nice"], 0),
        question(
          "Hur gammal är Tom?",
          ["Tjugotvå år", "Tolv år", "Sexton år"],
          2,
        ),
        question(
          "Vilket djur har de?",
          ["En hund", "En svart katt", "En vit katt"],
          1,
        ),
        question(
          "Vad gör Léa på helgen?",
          ["Läser och spelar gitarr", "Simmar", "Arbetar"],
          0,
        ),
      ],
    ),
    text(
      "text-au-cafe",
      "Au café",
      "— Bonjour, madame. Qu'est-ce que vous voulez ?\n— Bonjour. Un café et un croissant, s'il vous plaît.\n— Avec du lait ?\n— Non, merci. Sans lait.\n— Voilà. Ça fait quatre euros cinquante.\n— Merci, au revoir !",
      "– Hej. Vad vill ni ha?\n– Hej. En kaffe och en croissant, tack.\n– Med mjölk?\n– Nej tack. Utan mjölk.\n– Varsågod. Det blir fyra euro och femtio cent.\n– Tack, hej då!",
      [
        question(
          "Vad beställer kvinnan?",
          ["Ett te och en kaka", "En juice", "En kaffe och en croissant"],
          2,
        ),
        question("Vill hon ha mjölk i kaffet?", ["Ja", "Nej", "Lite"], 1),
        question(
          "Hur mycket kostar det?",
          ["4,50 euro", "5,40 euro", "4 euro"],
          0,
        ),
      ],
    ),
    text(
      "text-ma-journee",
      "Ma journée",
      "Le matin, je me lève à sept heures. Je prends une douche et je mange du pain avec de la confiture.\nJe vais au travail en bus. À midi, je mange au restaurant avec mes collègues.\nLe soir, je rentre à la maison et je regarde la télévision. Je me couche à onze heures.",
      "På morgonen går jag upp klockan sju. Jag duschar och äter bröd med sylt.\nJag åker buss till jobbet. Mitt på dagen äter jag på restaurang med mina kollegor.\nPå kvällen åker jag hem och tittar på tv. Jag lägger mig klockan elva.",
      [
        question(
          "När går personen upp?",
          ["Klockan sex", "Klockan åtta", "Klockan sju"],
          2,
        ),
        question(
          "Hur tar sig personen till jobbet?",
          ["Med bil", "Med buss", "Till fots"],
          1,
        ),
        question(
          "Var äter personen lunch?",
          ["På restaurang", "Hemma", "På kontoret"],
          0,
        ),
        question(
          "Vad gör personen på kvällen?",
          ["Läser en bok", "Springer", "Tittar på tv"],
          2,
        ),
      ],
    ),
    text(
      "text-ma-famille",
      "Ma famille",
      "Voici ma famille. Mon père s'appelle Marc. Il est médecin.\nMa mère s'appelle Claire. Elle est professeur de français.\nJ'ai deux sœurs, Julie et Emma. Julie a dix ans et Emma a quatorze ans.\nNos grands-parents habitent à la campagne. Nous allons chez eux en été.",
      "Det här är min familj. Min pappa heter Marc. Han är läkare.\nMin mamma heter Claire. Hon är lärare i franska.\nJag har två systrar, Julie och Emma. Julie är tio år och Emma är fjorton år.\nVåra far- och morföräldrar bor på landet. Vi hälsar på dem på sommaren.",
      [
        question(
          "Vad arbetar pappan med?",
          ["Han är lärare", "Han är läkare", "Han är kock"],
          1,
        ),
        question("Hur många systrar har personen?", ["Två", "En", "Tre"], 0),
        question(
          "Var bor far- och morföräldrarna?",
          ["I stan", "Vid havet", "På landet"],
          2,
        ),
        question(
          "När hälsar familjen på dem?",
          ["På vintern", "På sommaren", "Varje helg"],
          1,
        ),
      ],
    ),
    text(
      "text-boulangerie",
      "À la boulangerie",
      "— Bonjour, monsieur !\n— Bonjour ! Je voudrais une baguette et deux croissants, s'il vous plaît.\n— Bien sûr. Et avec ça ?\n— Un gâteau au chocolat, aussi.\n— D'accord. Ça fait huit euros.\n— Voilà dix euros.\n— Merci. Voici votre monnaie.",
      "– Hej!\n– Hej! Jag skulle vilja ha en baguette och två croissanter, tack.\n– Självklart. Något mer?\n– En chokladtårta också.\n– Okej. Det blir åtta euro.\n– Här är tio euro.\n– Tack. Här är er växel.",
      [
        question("Hur många croissanter köper mannen?", ["Två", "En", "Tre"], 0),
        question(
          "Vilken sorts tårta köper han?",
          ["Jordgubbstårta", "Citrontårta", "Chokladtårta"],
          2,
        ),
        question(
          "Hur mycket betalar han med?",
          ["Åtta euro", "Tio euro", "Tjugo euro"],
          1,
        ),
      ],
    ),
    text(
      "text-le-week-end",
      "Le week-end",
      "Le samedi, il fait souvent beau. Avec mes amis, nous allons au parc.\nNous jouons au football et nous mangeons des sandwichs.\nLe dimanche, je reste à la maison. Je lis un livre, j'écoute de la musique et je téléphone à ma grand-mère.",
      "På lördagarna är det ofta fint väder. Jag och mina vänner går till parken.\nVi spelar fotboll och äter smörgåsar.\nPå söndagarna är jag hemma. Jag läser en bok, lyssnar på musik och ringer till min mormor.",
      [
        question(
          "Vad gör vännerna i parken?",
          ["Spelar fotboll", "Spelar tennis", "Simmar"],
          0,
        ),
        question("Vad äter de?", ["Pizza", "Glass", "Smörgåsar"], 2),
        question(
          "Vem ringer personen till på söndagen?",
          ["Sin bror", "Sin mormor", "Sin mamma"],
          1,
        ),
      ],
    ),
    // Fler texter
    text(
      "text-a-la-gare",
      "À la gare",
      "— Bonjour, un billet pour Paris, s'il vous plaît.\n— Aller simple ou aller-retour ?\n— Aller-retour.\n— Pour quel jour ?\n— Pour demain matin.\n— Le train part à huit heures et quart. Ça fait quarante-deux euros.\n— Voilà. Merci !",
      "– Hej, en biljett till Paris, tack.\n– Enkel eller tur och retur?\n– Tur och retur.\n– För vilken dag?\n– För i morgon bitti.\n– Tåget går kvart över åtta. Det blir fyrtiotvå euro.\n– Varsågod. Tack!",
      [
        question(
          "Vart ska personen åka?",
          ["Till Paris", "Till Lyon", "Till Marseille"],
          0,
        ),
        question(
          "Vilken sorts biljett köper personen?",
          ["Enkel", "Ett månadskort", "Tur och retur"],
          2,
        ),
        question(
          "När går tåget?",
          ["Halv nio", "Kvart över åtta", "Klockan åtta"],
          1,
        ),
        question("Vad kostar biljetten?", ["42 euro", "24 euro", "52 euro"], 0),
      ],
    ),
    text(
      "text-mon-appartement",
      "Mon appartement",
      "J'habite dans un petit appartement au troisième étage. Il y a une cuisine, un salon et une chambre.\nDans le salon, il y a un canapé bleu et une grande table.\nMa chambre est petite, mais elle a une fenêtre avec une belle vue sur le parc. J'aime beaucoup mon appartement.",
      "Jag bor i en liten lägenhet på tredje våningen. Det finns ett kök, ett vardagsrum och ett sovrum.\nI vardagsrummet finns en blå soffa och ett stort bord.\nMitt sovrum är litet, men det har ett fönster med fin utsikt över parken. Jag tycker mycket om min lägenhet.",
      [
        question(
          "På vilken våning bor personen?",
          ["På andra", "På fjärde", "På tredje"],
          2,
        ),
        question("Vilken färg har soffan?", ["Röd", "Blå", "Grön"], 1),
        question(
          "Vad ser man från sovrumsfönstret?",
          ["En park", "Havet", "En kyrka"],
          0,
        ),
      ],
    ),
    text(
      "text-au-marche",
      "Au marché",
      "Le samedi matin, je vais au marché avec ma mère.\nNous achetons des légumes, des fruits et du fromage. Les tomates sont très bonnes en été.\nMa mère parle avec le vendeur de fromage, il est très sympathique.\nAprès le marché, nous buvons un café ensemble.",
      "På lördagsmorgnarna går jag till marknaden med min mamma.\nVi köper grönsaker, frukt och ost. Tomaterna är väldigt goda på sommaren.\nMin mamma pratar med ostförsäljaren, han är väldigt trevlig.\nEfter marknaden dricker vi kaffe tillsammans.",
      [
        question(
          "När går personen till marknaden?",
          ["På söndagskvällarna", "På måndagsmorgnarna", "På lördagsmorgnarna"],
          2,
        ),
        question(
          "Vem går personen dit med?",
          ["Sin bror", "Sin mamma", "En vän"],
          1,
        ),
        question(
          "Vad gör de efter marknaden?",
          ["Dricker kaffe", "Äter lunch", "Går hem"],
          0,
        ),
      ],
    ),
    text(
      "text-mon-ami-lucas",
      "Mon ami Lucas",
      "Lucas est mon meilleur ami. Il a vingt-cinq ans et il habite à Marseille.\nIl est grand, il a les cheveux noirs et les yeux bleus. Il travaille dans une banque.\nIl aime le sport : il joue au tennis le mardi et il nage le jeudi.\nLe week-end, nous allons souvent au cinéma.",
      "Lucas är min bästa vän. Han är tjugofem år och bor i Marseille.\nHan är lång, har svart hår och blå ögon. Han arbetar på en bank.\nHan tycker om sport: han spelar tennis på tisdagarna och simmar på torsdagarna.\nPå helgerna går vi ofta på bio.",
      [
        question("Var bor Lucas?", ["I Paris", "I Bordeaux", "I Marseille"], 2),
        question(
          "Var arbetar han?",
          ["På ett sjukhus", "På en bank", "I en skola"],
          1,
        ),
        question(
          "Vad gör han på torsdagarna?",
          ["Han simmar", "Han spelar tennis", "Han springer"],
          0,
        ),
        question(
          "Vad gör vännerna ofta på helgerna?",
          ["Lagar mat", "Åker till havet", "Går på bio"],
          2,
        ),
      ],
    ),
    text(
      "text-le-temps-en-suede",
      "Le temps en Suède",
      "En Suède, l'hiver est long et froid. Il neige souvent et il fait nuit tôt, vers trois heures de l'après-midi.\nAu printemps, les jours sont plus longs.\nL'été est court mais très beau : il fait jour presque toute la nuit. Les Suédois aiment beaucoup l'été !",
      "I Sverige är vintern lång och kall. Det snöar ofta och det blir mörkt tidigt, vid tretiden på eftermiddagen.\nPå våren blir dagarna längre.\nSommaren är kort men väldigt vacker: det är ljust nästan hela natten. Svenskarna tycker väldigt mycket om sommaren!",
      [
        question(
          "Hur är vintern i Sverige?",
          ["Kort och mild", "Lång och kall", "Varm"],
          1,
        ),
        question(
          "När blir det mörkt på vintern?",
          ["Vid tretiden", "Vid femtiden", "Vid sjutiden"],
          0,
        ),
        question(
          "Hur är sommaren?",
          ["Lång och regnig", "Varm och torr", "Kort men vacker"],
          2,
        ),
      ],
    ),
    text(
      "text-carte-postale",
      "Une carte postale",
      "Chère Marie,\nJe suis en vacances à la montagne avec ma famille. Il fait beau et chaud.\nLe matin, nous marchons dans la forêt et l'après-midi, nous nageons dans le lac.\nL'hôtel est petit mais très joli. Je rentre dimanche.\nBisous, Anna",
      "Kära Marie,\nJag är på semester i bergen med min familj. Det är fint och varmt väder.\nPå förmiddagarna vandrar vi i skogen och på eftermiddagarna badar vi i sjön.\nHotellet är litet men väldigt fint. Jag åker hem på söndag.\nKram, Anna",
      [
        question(
          "Var är Anna på semester?",
          ["Vid havet", "I bergen", "I en storstad"],
          1,
        ),
        question(
          "Vad gör de på eftermiddagarna?",
          ["Badar i sjön", "Vandrar i skogen", "Sover"],
          0,
        ),
        question(
          "När åker Anna hem?",
          ["På lördag", "På måndag", "På söndag"],
          2,
        ),
      ],
    ),
    text(
      "text-au-restaurant",
      "Au restaurant",
      "— Bonsoir. Une table pour deux personnes ?\n— Oui, s'il vous plaît.\n— Voici la carte. Qu'est-ce que vous voulez boire ?\n— Une bouteille d'eau et deux verres de vin rouge.\n— Et comme plat ?\n— Pour moi, le poisson. Et pour mon mari, le poulet avec des légumes.\n— Très bien.",
      "– God kväll. Ett bord för två personer?\n– Ja, tack.\n– Här är menyn. Vad vill ni dricka?\n– En flaska vatten och två glas rött vin.\n– Och vad vill ni äta?\n– Fisken till mig. Och kycklingen med grönsaker till min man.\n– Utmärkt.",
      [
        question("Hur många personer är de?", ["En", "Två", "Fyra"], 1),
        question("Vad dricker de?", ["Vatten och rött vin", "Öl", "Juice"], 0),
        question(
          "Vad äter mannen?",
          ["Fisk", "Pizza", "Kyckling med grönsaker"],
          2,
        ),
      ],
    ),
  ]
}

fn entry(id: String, theme: String, sv: List(String), word: Word) -> Entry {
  Entry(id:, level: A1, theme:, sv:, word:)
}

fn phrase(id, theme, sv, fr) -> Entry {
  entry(id, theme, sv, Expression(fr))
}

fn noun(id, theme, fr, gender, sv) -> Entry {
  entry(id, theme, sv, lexicon.noun(fr, gender))
}

/// `forms` are the présent forms; `participle` and `auxiliary` give the
/// passé composé.
fn verb(id, sv, infinitive, forms, participle, auxiliary) -> Entry {
  let #(je, tu, il, nous, vous, ils) = forms
  entry(
    id,
    "verb",
    sv,
    Verb(
      infinitive:,
      present: Present(je:, tu:, il:, nous:, vous:, ils:),
      participle:,
      auxiliary:,
      reflexive: False,
    ),
  )
}

/// A sentence with a `___` gap, its Swedish translation, the accepted
/// answers for the gap and a hint ("" for none).
fn sentence(id, theme, sv, text, answers, hint) -> Entry {
  entry(id, theme, [sv], Sentence(text:, answers:, hint:))
}

fn adjective(id, theme, sv, masculine, feminine) -> Entry {
  entry(id, theme, sv, lexicon.adjective(masculine, feminine))
}

fn invariable(id, theme, sv, form) -> Entry {
  entry(id, theme, sv, lexicon.invariable_adjective(form))
}

/// A reflexive verb, given without its pronoun ("lever" for se lever). It
/// takes être in the passé composé.
fn reflexive(id, sv, infinitive, forms, participle) -> Entry {
  let #(je, tu, il, nous, vous, ils) = forms
  entry(
    id,
    "verb",
    sv,
    Verb(
      infinitive:,
      present: Present(je:, tu:, il:, nous:, vous:, ils:),
      participle:,
      auxiliary: Etre,
      reflexive: True,
    ),
  )
}

/// A sentence to make negative, the Swedish meaning of the negative one and
/// the accepted negative sentences.
fn negate(id, sv, source, answers) -> Entry {
  entry(id, "negation", [sv], Rewrite(task: Negate, source:, answers:))
}

/// A text with its Swedish translation and comprehension questions.
fn text(id, title, french, swedish, questions) -> Entry {
  entry(id, "texter", [title], Text(title:, french:, swedish:, questions:))
}

fn question(question, options, answer) -> Question {
  Question(question:, options:, answer:)
}
