//// A2 vocabulary. Ids are stored with the learner's progress: never rename
//// or reuse one. Put the canonical translation first in `sv`.

import franska/lexicon.{
  type Entry, type Question, type Word, A2, Avoir, Entry, Etre, Expression,
  Feminine, Masculine, Negate, Present, Question, Rewrite, Sentence, Text,
  UsePronoun, Verb,
}

pub fn entries() -> List(Entry) {
  [
    // Vardagsfraser
    phrase("je-ne-sais-pas", "vardagsfraser", ["jag vet inte"], [
      "je ne sais pas", "je sais pas",
    ]),
    phrase("je-ne-comprends-pas", "vardagsfraser", ["jag förstår inte"], [
      "je ne comprends pas", "je comprends pas",
    ]),
    phrase(
      "pouvez-vous-repeter",
      "vardagsfraser",
      ["kan du upprepa?", "kan ni upprepa?"],
      ["pouvez-vous répéter ?", "vous pouvez répéter ?", "tu peux répéter ?"],
    ),
    phrase("combien-ca-coute", "vardagsfraser", ["vad kostar det?"], [
      "combien ça coûte ?", "ça coûte combien ?", "c'est combien ?",
    ]),
    phrase("quelle-heure-est-il", "vardagsfraser", ["vad är klockan?"], [
      "quelle heure est-il ?", "il est quelle heure ?",
    ]),
    phrase(
      "je-voudrais",
      "vardagsfraser",
      ["jag skulle vilja", "jag vill gärna", "jag vill ha"],
      [
        "je voudrais",
      ],
    ),
    phrase("j-ai-faim", "vardagsfraser", ["jag är hungrig"], ["j'ai faim"]),
    phrase("j-ai-soif", "vardagsfraser", ["jag är törstig"], ["j'ai soif"]),
    phrase("j-ai-froid", "vardagsfraser", ["jag fryser"], ["j'ai froid"]),
    phrase("d-accord", "vardagsfraser", ["okej", "ok", "visst"], ["d'accord"]),
    phrase("de-rien", "vardagsfraser", ["ingen orsak", "varsågod"], [
      "de rien",
    ]),
    phrase("bon-appetit", "vardagsfraser", ["smaklig måltid"], [
      "bon appétit",
    ]),
    phrase("a-bientot", "vardagsfraser", ["vi ses snart", "på återseende"], [
      "à bientôt",
    ]),
    // Tid
    phrase("aujourd-hui", "tid", ["i dag", "idag"], ["aujourd'hui"]),
    phrase("demain", "tid", ["i morgon", "imorgon"], ["demain"]),
    phrase("hier", "tid", ["i går", "igår"], ["hier"]),
    phrase("maintenant", "tid", ["nu"], ["maintenant"]),
    phrase("toujours", "tid", ["alltid", "fortfarande"], ["toujours"]),
    phrase("souvent", "tid", ["ofta"], ["souvent"]),
    noun("jour", "tid", "jour", Masculine, ["dag"]),
    noun("semaine", "tid", "semaine", Feminine, ["vecka"]),
    noun("mois", "tid", "mois", Masculine, ["månad"]),
    noun("annee", "tid", "année", Feminine, ["år"]),
    noun("heure", "tid", "heure", Feminine, ["timme"]),
    noun("matin", "tid", "matin", Masculine, ["morgon", "förmiddag"]),
    noun("soir", "tid", "soir", Masculine, ["kväll"]),
    // Väder och natur
    phrase(
      "il-fait-beau",
      "väder",
      ["det är fint väder", "det är vackert väder"],
      ["il fait beau"],
    ),
    phrase("il-pleut", "väder", ["det regnar"], ["il pleut"]),
    phrase("il-fait-froid", "väder", ["det är kallt"], ["il fait froid"]),
    phrase("il-fait-chaud", "väder", ["det är varmt"], ["il fait chaud"]),
    noun("soleil", "väder", "soleil", Masculine, ["sol"]),
    noun("pluie", "väder", "pluie", Feminine, ["regn"]),
    noun("neige", "väder", "neige", Feminine, ["snö"]),
    noun("vent", "väder", "vent", Masculine, ["vind", "blåst"]),
    noun("nuage", "väder", "nuage", Masculine, ["moln"]),
    noun("mer", "väder", "mer", Feminine, ["hav"]),
    noun("montagne", "väder", "montagne", Feminine, ["berg"]),
    noun("arbre", "väder", "arbre", Masculine, ["träd"]),
    noun("fleur", "väder", "fleur", Feminine, ["blomma"]),
    // Kläder
    noun("chemise", "kläder", "chemise", Feminine, ["skjorta"]),
    noun("pantalon", "kläder", "pantalon", Masculine, ["byxor", "byxa"]),
    noun("robe", "kläder", "robe", Feminine, ["klänning"]),
    noun("jupe", "kläder", "jupe", Feminine, ["kjol"]),
    noun("chaussure", "kläder", "chaussure", Feminine, ["sko"]),
    noun("manteau", "kläder", "manteau", Masculine, ["kappa", "rock"]),
    noun("veste", "kläder", "veste", Feminine, ["jacka", "kavaj"]),
    noun("chapeau", "kläder", "chapeau", Masculine, ["hatt"]),
    // Kroppen
    noun("tete", "kroppen", "tête", Feminine, ["huvud"]),
    noun("main", "kroppen", "main", Feminine, ["hand"]),
    noun("bras", "kroppen", "bras", Masculine, ["arm"]),
    noun("jambe", "kroppen", "jambe", Feminine, ["ben"]),
    noun("pied", "kroppen", "pied", Masculine, ["fot"]),
    noun("oeil", "kroppen", "œil", Masculine, ["öga"]),
    noun("bouche", "kroppen", "bouche", Feminine, ["mun"]),
    noun("dos", "kroppen", "dos", Masculine, ["rygg"]),
    noun("coeur", "kroppen", "cœur", Masculine, ["hjärta"]),
    // Resor
    noun("voyage", "resor", "voyage", Masculine, ["resa"]),
    noun("avion", "resor", "avion", Masculine, ["flygplan", "plan"]),
    noun("train", "resor", "train", Masculine, ["tåg"]),
    noun("billet", "resor", "billet", Masculine, ["biljett"]),
    noun("valise", "resor", "valise", Feminine, ["resväska", "väska"]),
    noun("hotel", "resor", "hôtel", Masculine, ["hotell"]),
    noun("plage", "resor", "plage", Feminine, ["strand"]),
    noun("pays", "resor", "pays", Masculine, ["land"]),
    noun("cle", "resor", "clé", Feminine, ["nyckel"]),
    // Arbete
    noun("travail", "arbete", "travail", Masculine, ["arbete", "jobb"]),
    noun("bureau", "arbete", "bureau", Masculine, ["kontor", "skrivbord"]),
    noun("argent", "arbete", "argent", Masculine, ["pengar"]),
    noun("medecin", "arbete", "médecin", Masculine, ["läkare"]),
    noun("professeur", "arbete", "professeur", Masculine, ["lärare"]),
    noun("ordinateur", "arbete", "ordinateur", Masculine, ["dator"]),
    noun("reunion", "arbete", "réunion", Feminine, ["möte"]),
    // Fler verb
    verb(
      "venir",
      ["komma"],
      "venir",
      #("viens", "viens", "vient", "venons", "venez", "viennent"),
      "venu",
      Etre,
    ),
    verb(
      "voir",
      ["se"],
      "voir",
      #("vois", "vois", "voit", "voyons", "voyez", "voient"),
      "vu",
      Avoir,
    ),
    verb(
      "savoir",
      ["veta", "kunna"],
      "savoir",
      #("sais", "sais", "sait", "savons", "savez", "savent"),
      "su",
      Avoir,
    ),
    verb(
      "dire",
      ["säga"],
      "dire",
      #("dis", "dis", "dit", "disons", "dites", "disent"),
      "dit",
      Avoir,
    ),
    verb(
      "mettre",
      ["sätta", "lägga", "ställa", "ta på sig"],
      "mettre",
      #("mets", "mets", "met", "mettons", "mettez", "mettent"),
      "mis",
      Avoir,
    ),
    verb(
      "partir",
      ["åka iväg", "ge sig av", "gå"],
      "partir",
      #("pars", "pars", "part", "partons", "partez", "partent"),
      "parti",
      Etre,
    ),
    verb(
      "sortir",
      ["gå ut"],
      "sortir",
      #("sors", "sors", "sort", "sortons", "sortez", "sortent"),
      "sorti",
      Etre,
    ),
    verb(
      "dormir",
      ["sova"],
      "dormir",
      #("dors", "dors", "dort", "dormons", "dormez", "dorment"),
      "dormi",
      Avoir,
    ),
    verb(
      "lire",
      ["läsa"],
      "lire",
      #("lis", "lis", "lit", "lisons", "lisez", "lisent"),
      "lu",
      Avoir,
    ),
    verb(
      "ecrire",
      ["skriva"],
      "écrire",
      #("écris", "écris", "écrit", "écrivons", "écrivez", "écrivent"),
      "écrit",
      Avoir,
    ),
    verb(
      "finir",
      ["avsluta", "bli klar", "sluta"],
      "finir",
      #("finis", "finis", "finit", "finissons", "finissez", "finissent"),
      "fini",
      Avoir,
    ),
    verb(
      "acheter",
      ["köpa"],
      "acheter",
      #("achète", "achètes", "achète", "achetons", "achetez", "achètent"),
      "acheté",
      Avoir,
    ),
    verb(
      "appeler",
      ["ringa", "kalla"],
      "appeler",
      #("appelle", "appelles", "appelle", "appelons", "appelez", "appellent"),
      "appelé",
      Avoir,
    ),
    verb(
      "attendre",
      ["vänta", "vänta på"],
      "attendre",
      #("attends", "attends", "attend", "attendons", "attendez", "attendent"),
      "attendu",
      Avoir,
    ),
    verb(
      "comprendre",
      ["förstå"],
      "comprendre",
      #(
        "comprends",
        "comprends",
        "comprend",
        "comprenons",
        "comprenez",
        "comprennent",
      ),
      "compris",
      Avoir,
    ),
    verb(
      "connaitre",
      ["känna", "känna till"],
      "connaître",
      #(
        "connais",
        "connais",
        "connaît",
        "connaissons",
        "connaissez",
        "connaissent",
      ),
      "connu",
      Avoir,
    ),
    verb(
      "devoir",
      ["måste", "vara tvungen"],
      "devoir",
      #("dois", "dois", "doit", "devons", "devez", "doivent"),
      "dû",
      Avoir,
    ),
    verb(
      "travailler",
      ["arbeta", "jobba"],
      "travailler",
      #(
        "travaille",
        "travailles",
        "travaille",
        "travaillons",
        "travaillez",
        "travaillent",
      ),
      "travaillé",
      Avoir,
    ),
    verb(
      "regarder",
      ["titta på", "titta", "se på"],
      "regarder",
      #("regarde", "regardes", "regarde", "regardons", "regardez", "regardent"),
      "regardé",
      Avoir,
    ),
    verb(
      "ecouter",
      ["lyssna", "lyssna på"],
      "écouter",
      #("écoute", "écoutes", "écoute", "écoutons", "écoutez", "écoutent"),
      "écouté",
      Avoir,
    ),
    // Fler verb
    verb(
      "vendre",
      ["sälja"],
      "vendre",
      #("vends", "vends", "vend", "vendons", "vendez", "vendent"),
      "vendu",
      Avoir,
    ),
    verb(
      "preferer",
      ["föredra"],
      "préférer",
      #("préfère", "préfères", "préfère", "préférons", "préférez", "préfèrent"),
      "préféré",
      Avoir,
    ),
    verb(
      "rentrer",
      ["komma hem", "gå hem", "åka hem"],
      "rentrer",
      #("rentre", "rentres", "rentre", "rentrons", "rentrez", "rentrent"),
      "rentré",
      Etre,
    ),
    // Reflexiva verb
    reflexive(
      "se-promener",
      ["promenera", "gå på promenad"],
      "promener",
      #("promène", "promènes", "promène", "promenons", "promenez", "promènent"),
      "promené",
    ),
    reflexive(
      "se-depecher",
      ["skynda sig"],
      "dépêcher",
      #("dépêche", "dépêches", "dépêche", "dépêchons", "dépêchez", "dépêchent"),
      "dépêché",
    ),
    reflexive(
      "s-amuser",
      ["ha roligt"],
      "amuser",
      #("amuse", "amuses", "amuse", "amusons", "amusez", "amusent"),
      "amusé",
    ),
    reflexive(
      "se-reposer",
      ["vila sig", "vila"],
      "reposer",
      #("repose", "reposes", "repose", "reposons", "reposez", "reposent"),
      "reposé",
    ),
    // Adjektiv
    adjective("heureux", "egenskaper", ["lycklig"], "heureux", "heureuse"),
    adjective("triste", "egenskaper", ["ledsen"], "triste", "triste"),
    adjective("important", "egenskaper", ["viktig"], "important", "importante"),
    adjective("libre", "egenskaper", ["fri", "ledig"], "libre", "libre"),
    adjective("plein", "egenskaper", ["full"], "plein", "pleine"),
    adjective("vide", "egenskaper", ["tom"], "vide", "vide"),
    adjective("rapide", "egenskaper", ["snabb"], "rapide", "rapide"),
    adjective("lent", "egenskaper", ["långsam"], "lent", "lente"),
    adjective("propre", "egenskaper", ["ren"], "propre", "propre"),
    adjective("sale", "egenskaper", ["smutsig"], "sale", "sale"),
    adjective("fort", "egenskaper", ["stark"], "fort", "forte"),
    adjective("malade", "egenskaper", ["sjuk"], "malade", "malade"),
    adjective("pret", "egenskaper", ["redo", "klar"], "prêt", "prête"),
    adjective("gros", "egenskaper", ["tjock"], "gros", "grosse"),
    // Mer vokabulär (A2)
    noun("sante", "hälsa", "santé", Feminine, ["hälsa"]),
    noun("medicament", "hälsa", "médicament", Masculine, [
      "medicin",
      "läkemedel",
    ]),
    noun("douleur", "hälsa", "douleur", Feminine, ["smärta", "värk"]),
    noun("fievre", "hälsa", "fièvre", Feminine, ["feber"]),
    noun("rhume", "hälsa", "rhume", Masculine, ["förkylning"]),
    noun("dentiste", "hälsa", "dentiste", Masculine, ["tandläkare"]),
    noun("infirmiere", "hälsa", "infirmière", Feminine, ["sjuksköterska"]),
    noun("accident", "hälsa", "accident", Masculine, ["olycka"]),
    noun("sang", "hälsa", "sang", Masculine, ["blod"]),
    noun("grippe", "hälsa", "grippe", Feminine, ["influensa"]),
    phrase("j-ai-mal-a-la-tete", "hälsa", ["jag har ont i huvudet"], [
      "j'ai mal à la tête",
    ]),
    phrase("j-ai-mal", "hälsa", ["jag har ont"], ["j'ai mal"]),
    phrase("ca-fait-mal", "hälsa", ["det gör ont"], ["ça fait mal"]),
    phrase("au-secours", "hälsa", ["hjälp!"], ["au secours !"]),
    noun("avocat", "yrken", "avocat", Masculine, ["advokat"]),
    noun("policier", "yrken", "policier", Masculine, ["polis", "polisman"]),
    noun("boulanger", "yrken", "boulanger", Masculine, ["bagare"]),
    noun("cuisinier", "yrken", "cuisinier", Masculine, ["kock"]),
    noun("serveur", "yrken", "serveur", Masculine, ["servitör"]),
    noun("vendeur", "yrken", "vendeur", Masculine, ["försäljare", "expedit"]),
    noun("ingenieur", "yrken", "ingénieur", Masculine, ["ingenjör"]),
    noun("pompier", "yrken", "pompier", Masculine, ["brandman"]),
    noun("facteur", "yrken", "facteur", Masculine, ["brevbärare"]),
    noun("acteur", "yrken", "acteur", Masculine, ["skådespelare"]),
    noun("chanteur", "yrken", "chanteur", Masculine, ["sångare"]),
    noun("journaliste", "yrken", "journaliste", Masculine, ["journalist"]),
    noun("agriculteur", "yrken", "agriculteur", Masculine, [
      "bonde",
      "lantbrukare",
    ]),
    noun("chauffeur", "yrken", "chauffeur", Masculine, ["chaufför", "förare"]),
    noun("patron", "yrken", "patron", Masculine, ["chef"]),
    noun("collegue", "yrken", "collègue", Masculine, ["kollega"]),
    noun("entreprise", "yrken", "entreprise", Feminine, ["företag"]),
    noun("salaire", "yrken", "salaire", Masculine, ["lön"]),
    noun("metier", "yrken", "métier", Masculine, ["yrke"]),
    noun("prix", "shopping", "prix", Masculine, ["pris"]),
    noun("caisse", "shopping", "caisse", Feminine, ["kassa"]),
    noun("client", "shopping", "client", Masculine, ["kund"]),
    noun("carte", "shopping", "carte", Feminine, ["karta", "kort", "meny"]),
    noun("recu", "shopping", "reçu", Masculine, ["kvitto"]),
    noun("taille", "shopping", "taille", Feminine, ["storlek"]),
    noun("cadeau", "shopping", "cadeau", Masculine, ["present", "gåva"]),
    noun("boutique", "shopping", "boutique", Feminine, ["butik"]),
    noun("euro", "shopping", "euro", Masculine, ["euro"]),
    noun("monnaie", "shopping", "monnaie", Feminine, ["växel", "småpengar"]),
    noun("liste", "shopping", "liste", Feminine, ["lista"]),
    noun("panier", "shopping", "panier", Masculine, ["korg"]),
    noun("foret", "natur", "forêt", Feminine, ["skog"]),
    noun("riviere", "natur", "rivière", Feminine, ["flod", "å"]),
    noun("lac", "natur", "lac", Masculine, ["sjö"]),
    noun("ile", "natur", "île", Feminine, ["ö"]),
    noun("campagne", "natur", "campagne", Feminine, ["landsbygd", "landet"]),
    noun("ciel", "natur", "ciel", Masculine, ["himmel"]),
    noun("etoile", "natur", "étoile", Feminine, ["stjärna"]),
    noun("lune", "natur", "lune", Feminine, ["måne"]),
    noun("terre", "natur", "terre", Feminine, ["jord"]),
    noun("champ", "natur", "champ", Masculine, ["fält", "åker"]),
    noun("herbe", "natur", "herbe", Feminine, ["gräs"]),
    noun("pierre", "natur", "pierre", Feminine, ["sten"]),
    noun("village", "natur", "village", Masculine, ["by"]),
    noun("bateau", "resor", "bateau", Masculine, ["båt"]),
    noun("port", "resor", "port", Masculine, ["hamn"]),
    noun("route", "resor", "route", Feminine, ["väg"]),
    noun("autoroute", "resor", "autoroute", Feminine, ["motorväg"]),
    noun("passeport", "resor", "passeport", Masculine, ["pass"]),
    noun("depart", "resor", "départ", Masculine, ["avgång"]),
    noun("arrivee", "resor", "arrivée", Feminine, ["ankomst"]),
    noun("quai", "resor", "quai", Masculine, ["perrong"]),
    noun("guichet", "resor", "guichet", Masculine, ["biljettlucka"]),
    noun("reservation", "resor", "réservation", Feminine, [
      "bokning",
      "reservation",
    ]),
    noun("touriste", "resor", "touriste", Masculine, ["turist"]),
    noun("joie", "känslor", "joie", Feminine, ["glädje"]),
    noun("peur", "känslor", "peur", Feminine, ["rädsla"]),
    noun("colere", "känslor", "colère", Feminine, ["ilska"]),
    noun("amour", "känslor", "amour", Masculine, ["kärlek"]),
    noun("tristesse", "känslor", "tristesse", Feminine, ["sorg"]),
    noun("surprise", "känslor", "surprise", Feminine, ["överraskning"]),
    noun("bonheur", "känslor", "bonheur", Masculine, ["lycka"]),
    noun("reve", "känslor", "rêve", Masculine, ["dröm"]),
    noun("idee", "känslor", "idée", Feminine, ["idé"]),
    phrase("j-ai-peur", "känslor", ["jag är rädd"], ["j'ai peur"]),
    adjective("fier", "egenskaper", ["stolt"], "fier", "fière"),
    adjective("nerveux", "egenskaper", ["nervös"], "nerveux", "nerveuse"),
    adjective("inquiet", "egenskaper", ["orolig"], "inquiet", "inquiète"),
    adjective("surpris", "egenskaper", ["förvånad"], "surpris", "surprise"),
    adjective("amoureux", "egenskaper", ["kär"], "amoureux", "amoureuse"),
    adjective("jaloux", "egenskaper", ["svartsjuk"], "jaloux", "jalouse"),
    adjective("poli", "egenskaper", ["artig"], "poli", "polie"),
    adjective("mechant", "egenskaper", ["elak"], "méchant", "méchante"),
    adjective(
      "serieux",
      "egenskaper",
      ["allvarlig", "seriös"],
      "sérieux",
      "sérieuse",
    ),
    adjective("timide", "egenskaper", ["blyg"], "timide", "timide"),
    adjective("moderne", "egenskaper", ["modern"], "moderne", "moderne"),
    adjective(
      "ancien",
      "egenskaper",
      ["före detta", "tidigare", "förra", "forntida", "gammal"],
      "ancien",
      "ancienne",
    ),
    adjective("dangereux", "egenskaper", ["farlig"], "dangereux", "dangereuse"),
    adjective("possible", "egenskaper", ["möjlig"], "possible", "possible"),
    adjective(
      "impossible",
      "egenskaper",
      ["omöjlig"],
      "impossible",
      "impossible",
    ),
    adjective(
      "necessaire",
      "egenskaper",
      ["nödvändig"],
      "nécessaire",
      "nécessaire",
    ),
    adjective(
      "different",
      "egenskaper",
      ["annorlunda", "olik"],
      "différent",
      "différente",
    ),
    adjective("pareil", "egenskaper", ["likadan"], "pareil", "pareille"),
    adjective("frais", "egenskaper", ["färsk", "sval"], "frais", "fraîche"),
    adjective("sec", "egenskaper", ["torr"], "sec", "sèche"),
    adjective("doux", "egenskaper", ["mjuk", "mild"], "doux", "douce"),
    adjective("dur", "egenskaper", ["hård"], "dur", "dure"),
    adjective(
      "tranquille",
      "egenskaper",
      ["stilla", "lugn"],
      "tranquille",
      "tranquille",
    ),
    verb(
      "devenir",
      ["bli"],
      "devenir",
      #("deviens", "deviens", "devient", "devenons", "devenez", "deviennent"),
      "devenu",
      Etre,
    ),
    verb(
      "revenir",
      ["komma tillbaka"],
      "revenir",
      #("reviens", "reviens", "revient", "revenons", "revenez", "reviennent"),
      "revenu",
      Etre,
    ),
    verb(
      "offrir",
      ["ge bort", "bjuda på", "ge"],
      "offrir",
      #("offre", "offres", "offre", "offrons", "offrez", "offrent"),
      "offert",
      Avoir,
    ),
    verb(
      "recevoir",
      ["få", "ta emot"],
      "recevoir",
      #("reçois", "reçois", "reçoit", "recevons", "recevez", "reçoivent"),
      "reçu",
      Avoir,
    ),
    verb(
      "envoyer",
      ["skicka"],
      "envoyer",
      #("envoie", "envoies", "envoie", "envoyons", "envoyez", "envoient"),
      "envoyé",
      Avoir,
    ),
    verb(
      "essayer",
      ["försöka", "prova"],
      "essayer",
      #("essaie", "essaies", "essaie", "essayons", "essayez", "essaient"),
      "essayé",
      Avoir,
    ),
    verb(
      "expliquer",
      ["förklara"],
      "expliquer",
      #(
        "explique",
        "expliques",
        "explique",
        "expliquons",
        "expliquez",
        "expliquent",
      ),
      "expliqué",
      Avoir,
    ),
    verb(
      "montrer",
      ["visa"],
      "montrer",
      #("montre", "montres", "montre", "montrons", "montrez", "montrent"),
      "montré",
      Avoir,
    ),
    verb(
      "decider",
      ["bestämma", "besluta"],
      "décider",
      #("décide", "décides", "décide", "décidons", "décidez", "décident"),
      "décidé",
      Avoir,
    ),
    verb(
      "reussir",
      ["lyckas"],
      "réussir",
      #(
        "réussis",
        "réussis",
        "réussit",
        "réussissons",
        "réussissez",
        "réussissent",
      ),
      "réussi",
      Avoir,
    ),
    verb(
      "choisir",
      ["välja"],
      "choisir",
      #(
        "choisis",
        "choisis",
        "choisit",
        "choisissons",
        "choisissez",
        "choisissent",
      ),
      "choisi",
      Avoir,
    ),
    verb(
      "perdre",
      ["förlora", "tappa"],
      "perdre",
      #("perds", "perds", "perd", "perdons", "perdez", "perdent"),
      "perdu",
      Avoir,
    ),
    verb(
      "gagner",
      ["vinna", "tjäna"],
      "gagner",
      #("gagne", "gagnes", "gagne", "gagnons", "gagnez", "gagnent"),
      "gagné",
      Avoir,
    ),
    verb(
      "conduire",
      ["köra"],
      "conduire",
      #(
        "conduis",
        "conduis",
        "conduit",
        "conduisons",
        "conduisez",
        "conduisent",
      ),
      "conduit",
      Avoir,
    ),
    verb(
      "vivre",
      ["leva"],
      "vivre",
      #("vis", "vis", "vit", "vivons", "vivez", "vivent"),
      "vécu",
      Avoir,
    ),
    verb(
      "laisser",
      ["låta", "lämna kvar"],
      "laisser",
      #("laisse", "laisses", "laisse", "laissons", "laissez", "laissent"),
      "laissé",
      Avoir,
    ),
    verb(
      "quitter",
      ["lämna"],
      "quitter",
      #("quitte", "quittes", "quitte", "quittons", "quittez", "quittent"),
      "quitté",
      Avoir,
    ),
    verb(
      "utiliser",
      ["använda"],
      "utiliser",
      #("utilise", "utilises", "utilise", "utilisons", "utilisez", "utilisent"),
      "utilisé",
      Avoir,
    ),
    verb(
      "preparer",
      ["förbereda", "laga"],
      "préparer",
      #("prépare", "prépares", "prépare", "préparons", "préparez", "préparent"),
      "préparé",
      Avoir,
    ),
    verb(
      "rencontrer",
      ["träffa", "möta"],
      "rencontrer",
      #(
        "rencontre",
        "rencontres",
        "rencontre",
        "rencontrons",
        "rencontrez",
        "rencontrent",
      ),
      "rencontré",
      Avoir,
    ),
    verb(
      "pleurer",
      ["gråta"],
      "pleurer",
      #("pleure", "pleures", "pleure", "pleurons", "pleurez", "pleurent"),
      "pleuré",
      Avoir,
    ),
    verb(
      "rire",
      ["skratta"],
      "rire",
      #("ris", "ris", "rit", "rions", "riez", "rient"),
      "ri",
      Avoir,
    ),
    verb(
      "esperer",
      ["hoppas"],
      "espérer",
      #("espère", "espères", "espère", "espérons", "espérez", "espèrent"),
      "espéré",
      Avoir,
    ),
    verb(
      "repeter",
      ["upprepa"],
      "répéter",
      #("répète", "répètes", "répète", "répétons", "répétez", "répètent"),
      "répété",
      Avoir,
    ),
    verb(
      "remercier",
      ["tacka"],
      "remercier",
      #(
        "remercie",
        "remercies",
        "remercie",
        "remercions",
        "remerciez",
        "remercient",
      ),
      "remercié",
      Avoir,
    ),
    verb(
      "changer",
      ["byta", "ändra"],
      "changer",
      #("change", "changes", "change", "changeons", "changez", "changent"),
      "changé",
      Avoir,
    ),
    verb(
      "continuer",
      ["fortsätta"],
      "continuer",
      #(
        "continue",
        "continues",
        "continue",
        "continuons",
        "continuez",
        "continuent",
      ),
      "continué",
      Avoir,
    ),
    reflexive(
      "se-sentir",
      ["må", "känna sig"],
      "sentir",
      #("sens", "sens", "sent", "sentons", "sentez", "sentent"),
      "senti",
    ),
    reflexive(
      "s-arreter",
      ["stanna upp", "stanna", "sluta", "stoppa"],
      "arrêter",
      #("arrête", "arrêtes", "arrête", "arrêtons", "arrêtez", "arrêtent"),
      "arrêté",
    ),
    // Ännu mer vokabulär (A2)
    noun("portable", "teknik", "portable", Masculine, ["mobil", "mobiltelefon"]),
    noun("ecran", "teknik", "écran", Masculine, ["skärm"]),
    noun("clavier", "teknik", "clavier", Masculine, ["tangentbord"]),
    noun("message", "teknik", "message", Masculine, ["meddelande"]),
    noun("e-mail", "teknik", "e-mail", Masculine, ["mejl", "e-post"]),
    noun("site", "teknik", "site", Masculine, ["webbplats", "sajt"]),
    noun("mot-de-passe", "teknik", "mot de passe", Masculine, ["lösenord"]),
    noun("application", "teknik", "application", Feminine, [
      "app",
      "applikation",
    ]),
    noun("video", "teknik", "vidéo", Feminine, ["video"]),
    noun("jeu-video", "teknik", "jeu vidéo", Masculine, ["datorspel", "tv-spel"]),
    noun("batterie", "teknik", "batterie", Feminine, ["batteri"]),
    noun("chargeur", "teknik", "chargeur", Masculine, ["laddare"]),
    noun("circulation", "staden", "circulation", Feminine, ["trafik"]),
    noun("trottoir", "staden", "trottoir", Masculine, ["trottoar"]),
    noun("carrefour", "staden", "carrefour", Masculine, ["korsning"]),
    noun("parking", "staden", "parking", Masculine, ["parkering"]),
    noun("batiment", "staden", "bâtiment", Masculine, ["byggnad"]),
    noun("mairie", "staden", "mairie", Feminine, ["rådhus", "kommunhus"]),
    noun("commissariat", "staden", "commissariat", Masculine, ["polisstation"]),
    noun("immeuble", "staden", "immeuble", Masculine, [
      "hyreshus",
      "flerbostadshus",
    ]),
    noun("ascenseur", "staden", "ascenseur", Masculine, ["hiss"]),
    noun("etage", "staden", "étage", Masculine, ["våning"]),
    noun("machine-a-laver", "hemmet", "machine à laver", Feminine, [
      "tvättmaskin",
    ]),
    noun("lave-vaisselle", "hemmet", "lave-vaisselle", Masculine, ["diskmaskin"]),
    noun("four", "hemmet", "four", Masculine, ["ugn"]),
    noun("poubelle", "hemmet", "poubelle", Feminine, ["soptunna", "papperskorg"]),
    noun("meuble", "hemmet", "meuble", Masculine, ["möbel"]),
    noun("loyer", "hemmet", "loyer", Masculine, ["hyran", "hyra"]),
    noun("proprietaire", "hemmet", "propriétaire", Masculine, [
      "hyresvärd",
      "ägare",
    ]),
    noun("balcon", "hemmet", "balcon", Masculine, ["balkong"]),
    noun("garage", "hemmet", "garage", Masculine, ["garage"]),
    noun("chauffage", "hemmet", "chauffage", Masculine, ["uppvärmning", "värme"]),
    noun("recette", "mat", "recette", Feminine, ["recept"]),
    noun("repas", "mat", "repas", Masculine, ["måltid"]),
    noun("boisson", "mat", "boisson", Feminine, ["dryck"]),
    noun("huile", "mat", "huile", Feminine, ["olja"]),
    noun("poivre", "mat", "poivre", Masculine, ["peppar"]),
    noun("farine", "mat", "farine", Feminine, ["mjöl"]),
    noun("ail", "mat", "ail", Masculine, ["vitlök"]),
    noun("champignon", "mat", "champignon", Masculine, ["svamp"]),
    noun("dessert", "mat", "dessert", Masculine, ["efterrätt", "dessert"]),
    noun("addition", "mat", "addition", Feminine, ["notan", "räkningen"]),
    noun("pourboire", "mat", "pourboire", Masculine, ["dricks"]),
    noun("costume", "kläder", "costume", Masculine, ["kostym"]),
    noun("cravate", "kläder", "cravate", Feminine, ["slips"]),
    noun("botte", "kläder", "botte", Feminine, ["stövel"]),
    noun("gant", "kläder", "gant", Masculine, ["handske", "vante"]),
    noun("poche", "kläder", "poche", Feminine, ["ficka"]),
    noun("bouton", "kläder", "bouton", Masculine, ["knapp"]),
    noun("mode", "kläder", "mode", Feminine, ["mode"]),
    noun("gorge", "hälsa", "gorge", Feminine, ["strupe", "hals"]),
    noun("peau", "hälsa", "peau", Feminine, ["hud"]),
    noun("os", "hälsa", "os", Masculine, ["skelettben", "ben"]),
    noun("ordonnance", "hälsa", "ordonnance", Feminine, [
      "läkarrecept",
      "recept",
    ]),
    noun("rendez-vous", "hälsa", "rendez-vous", Masculine, ["bokad tid", "möte"]),
    noun("urgences", "hälsa", "urgence", Feminine, ["akuten", "nödfall"]),
    noun("blessure", "hälsa", "blessure", Feminine, ["skada", "sår"]),
    noun("regime", "hälsa", "régime", Masculine, ["diet", "bantning"]),
    noun("sommeil", "hälsa", "sommeil", Masculine, ["sömn"]),
    noun("toux", "hälsa", "toux", Feminine, ["hostan", "hosta"]),
    noun("employe", "yrken", "employé", Masculine, ["anställd"]),
    noun("directeur", "yrken", "directeur", Masculine, ["direktör", "chef"]),
    noun("stage", "yrken", "stage", Masculine, ["praktik"]),
    noun("chomage", "yrken", "chômage", Masculine, ["arbetslöshet"]),
    noun("contrat", "yrken", "contrat", Masculine, ["kontrakt", "avtal"]),
    noun("entretien", "yrken", "entretien", Masculine, [
      "anställningsintervju",
      "intervju",
    ]),
    noun("usine", "yrken", "usine", Feminine, ["fabrik"]),
    noun("commercant", "yrken", "commerçant", Masculine, ["handlare"]),
    noun("plombier", "yrken", "plombier", Masculine, ["rörmokare"]),
    noun("electricien", "yrken", "électricien", Masculine, ["elektriker"]),
    noun("coiffeur", "yrken", "coiffeur", Masculine, ["frisör"]),
    noun("architecte", "yrken", "architecte", Masculine, ["arkitekt"]),
    noun("developpeur", "yrken", "développeur", Masculine, [
      "utvecklare",
      "programmerare",
    ]),
    noun("plante", "natur", "plante", Feminine, ["växt"]),
    noun("feuille", "natur", "feuille", Feminine, ["löv", "blad"]),
    noun("vallee", "natur", "vallée", Feminine, ["dal"]),
    noun("colline", "natur", "colline", Feminine, ["kulle"]),
    noun("desert", "natur", "désert", Masculine, ["öken"]),
    noun("ocean", "natur", "océan", Masculine, ["ocean", "världshav"]),
    noun("cote", "natur", "côte", Feminine, ["kust"]),
    noun("vague", "natur", "vague", Feminine, ["våg"]),
    noun("sable", "natur", "sable", Masculine, ["sand"]),
    noun("animal", "natur", "animal", Masculine, ["djur"]),
    noun("nature", "natur", "nature", Feminine, ["natur"]),
    noun("environnement", "natur", "environnement", Masculine, ["miljö"]),
    noun("pollution", "natur", "pollution", Feminine, [
      "förorening",
      "föroreningar",
    ]),
    noun("climat", "natur", "climat", Masculine, ["klimat"]),
    noun("temperature", "väder", "température", Feminine, ["temperatur"]),
    noun("degre", "väder", "degré", Masculine, ["grad"]),
    noun("orage", "väder", "orage", Masculine, ["åskväder", "åska"]),
    noun("brouillard", "väder", "brouillard", Masculine, ["dimma"]),
    noun("tempete", "väder", "tempête", Feminine, ["storm"]),
    noun("meteo", "väder", "météo", Feminine, [
      "väderprognos",
      "väderleksrapport",
    ]),
    noun("frontiere", "resor", "frontière", Feminine, ["gräns"]),
    noun("douane", "resor", "douane", Feminine, ["tull", "tullen"]),
    noun("vol", "resor", "vol", Masculine, ["flygning", "flyg"]),
    noun("carte-d-embarquement", "resor", "carte d'embarquement", Feminine, [
      "boardingkort",
    ]),
    noun("camping", "resor", "camping", Masculine, ["camping"]),
    noun("tente", "resor", "tente", Feminine, ["tält"]),
    noun("auberge-de-jeunesse", "resor", "auberge de jeunesse", Feminine, [
      "vandrarhem",
    ]),
    noun("guide", "resor", "guide", Masculine, ["guide"]),
    noun("plan", "resor", "plan", Masculine, ["stadskarta", "karta"]),
    noun("etranger", "resor", "étranger", Masculine, ["utlandet"]),
    noun("honte", "känslor", "honte", Feminine, ["skam"]),
    noun("ennui", "känslor", "ennui", Masculine, ["tristess", "leda"]),
    noun("inquietude", "känslor", "inquiétude", Feminine, ["oro"]),
    noun("confiance", "känslor", "confiance", Feminine, ["förtroende"]),
    noun("souvenir-nom", "känslor", "souvenir", Masculine, ["minne"]),
    noun("chance", "känslor", "chance", Feminine, ["tur", "chans"]),
    noun("fatigue-nom", "känslor", "fatigue", Feminine, ["trötthet"]),
    noun("stress", "känslor", "stress", Masculine, ["stress"]),
    phrase("j-ai-honte", "känslor", ["jag skäms"], ["j'ai honte"]),
    noun("exercice", "skolan", "exercice", Masculine, ["övning"]),
    noun("note", "skolan", "note", Feminine, ["betyg", "anteckning"]),
    noun("cours", "skolan", "cours", Masculine, ["kurs", "lektion"]),
    noun("diplome", "skolan", "diplôme", Masculine, ["diplom", "examensbevis"]),
    noun("matiere", "skolan", "matière", Feminine, ["skolämne", "ämne"]),
    noun("histoire", "skolan", "histoire", Feminine, ["historia", "berättelse"]),
    noun("geographie", "skolan", "géographie", Feminine, ["geografi"]),
    phrase("devoirs", "skolan", ["läxor", "läxa"], ["les devoirs"]),
    phrase("mathematiques", "skolan", ["matematik", "matte"], [
      "les mathématiques",
      "les maths",
    ]),
    phrase("d-abord", "småord", ["först"], ["d'abord"]),
    phrase("enfin", "småord", ["äntligen", "till slut"], ["enfin"]),
    phrase("depuis", "småord", ["ända sedan", "sedan"], ["depuis"]),
    phrase("presque", "småord", ["nästan"], ["presque"]),
    phrase("plutot", "småord", ["snarare", "hellre"], ["plutôt"]),
    phrase("surtout", "småord", ["framför allt"], ["surtout"]),
    phrase("environ", "småord", ["ungefär", "cirka"], ["environ"]),
    phrase("partout", "småord", ["överallt"], ["partout"]),
    phrase("quelque-part", "småord", ["någonstans"], ["quelque part"]),
    phrase("nulle-part", "småord", ["ingenstans"], ["nulle part"]),
    phrase("de-temps-en-temps", "småord", ["då och då"], ["de temps en temps"]),
    phrase("a-l-heure", "vardagsfraser", ["i tid"], ["à l'heure"]),
    phrase("en-retard", "vardagsfraser", ["försenad", "sen"], ["en retard"]),
    phrase("en-avance", "vardagsfraser", ["för tidigt", "i god tid"], [
      "en avance",
    ]),
    phrase("ca-depend", "vardagsfraser", ["det beror på"], ["ça dépend"]),
    phrase("j-ai-besoin-de", "vardagsfraser", ["jag behöver"], [
      "j'ai besoin de",
    ]),
    phrase("il-faut", "vardagsfraser", ["man måste", "det behövs"], ["il faut"]),
    phrase("je-suis-d-accord", "vardagsfraser", ["jag håller med"], [
      "je suis d'accord",
    ]),
    phrase("ca-ne-fait-rien", "vardagsfraser", ["det gör inget"], [
      "ça ne fait rien",
    ]),
    phrase("a-mon-avis", "vardagsfraser", ["enligt mig", "tycker jag"], [
      "à mon avis",
    ]),
    phrase("bonne-idee", "vardagsfraser", ["bra idé"], ["bonne idée"]),
    phrase("tant-pis", "vardagsfraser", ["synd", "strunt samma"], ["tant pis"]),
    adjective("fache", "egenskaper", ["arg"], "fâché", "fâchée"),
    adjective(
      "celibataire",
      "egenskaper",
      ["ogift", "singel"],
      "célibataire",
      "célibataire",
    ),
    adjective("marie", "egenskaper", ["gift"], "marié", "mariée"),
    adjective("occupe", "egenskaper", ["upptagen"], "occupé", "occupée"),
    adjective(
      "presse",
      "egenskaper",
      ["stressad", "pressad"],
      "pressé",
      "pressée",
    ),
    adjective("bruyant", "egenskaper", ["bullrig"], "bruyant", "bruyante"),
    adjective(
      "confortable",
      "egenskaper",
      ["bekväm"],
      "confortable",
      "confortable",
    ),
    adjective("pratique", "egenskaper", ["praktisk"], "pratique", "pratique"),
    adjective("utile", "egenskaper", ["nyttig", "användbar"], "utile", "utile"),
    adjective("inutile", "egenskaper", ["onödig"], "inutile", "inutile"),
    adjective("faible", "egenskaper", ["svag"], "faible", "faible"),
    adjective("mince", "egenskaper", ["smal"], "mince", "mince"),
    adjective("blond", "egenskaper", ["blond"], "blond", "blonde"),
    adjective("honnete", "egenskaper", ["ärlig"], "honnête", "honnête"),
    adjective("paresseux", "egenskaper", ["lat"], "paresseux", "paresseuse"),
    adjective("courageux", "egenskaper", ["modig"], "courageux", "courageuse"),
    adjective("curieux", "egenskaper", ["nyfiken"], "curieux", "curieuse"),
    adjective("sportif", "egenskaper", ["sportig"], "sportif", "sportive"),
    adjective(
      "genial",
      "egenskaper",
      ["fantastisk", "jättebra"],
      "génial",
      "géniale",
    ),
    adjective(
      "incroyable",
      "egenskaper",
      ["otrolig"],
      "incroyable",
      "incroyable",
    ),
    adjective("etrange", "egenskaper", ["konstig"], "étrange", "étrange"),
    adjective("normal", "egenskaper", ["normal"], "normal", "normale"),
    adjective("prive", "egenskaper", ["privat"], "privé", "privée"),
    adjective("gratuit", "egenskaper", ["gratis"], "gratuit", "gratuite"),
    verb(
      "tousser",
      ["hosta"],
      "tousser",
      #("tousse", "tousses", "tousse", "toussons", "toussez", "toussent"),
      "toussé",
      Avoir,
    ),
    verb(
      "louer",
      ["hyra"],
      "louer",
      #("loue", "loues", "loue", "louons", "louez", "louent"),
      "loué",
      Avoir,
    ),
    verb(
      "payer",
      ["betala"],
      "payer",
      #("paie", "paies", "paie", "payons", "payez", "paient"),
      "payé",
      Avoir,
    ),
    verb(
      "nettoyer",
      ["städa", "rengöra"],
      "nettoyer",
      #("nettoie", "nettoies", "nettoie", "nettoyons", "nettoyez", "nettoient"),
      "nettoyé",
      Avoir,
    ),
    verb(
      "demenager",
      ["flytta"],
      "déménager",
      #(
        "déménage",
        "déménages",
        "déménage",
        "déménageons",
        "déménagez",
        "déménagent",
      ),
      "déménagé",
      Avoir,
    ),
    verb(
      "emprunter",
      ["låna"],
      "emprunter",
      #(
        "emprunte",
        "empruntes",
        "emprunte",
        "empruntons",
        "empruntez",
        "empruntent",
      ),
      "emprunté",
      Avoir,
    ),
    verb(
      "preter",
      ["låna ut"],
      "prêter",
      #("prête", "prêtes", "prête", "prêtons", "prêtez", "prêtent"),
      "prêté",
      Avoir,
    ),
    verb(
      "reserver",
      ["boka"],
      "réserver",
      #("réserve", "réserves", "réserve", "réservons", "réservez", "réservent"),
      "réservé",
      Avoir,
    ),
    verb(
      "annuler",
      ["ställa in", "avboka"],
      "annuler",
      #("annule", "annules", "annule", "annulons", "annulez", "annulent"),
      "annulé",
      Avoir,
    ),
    verb(
      "reparer",
      ["reparera", "laga"],
      "réparer",
      #("répare", "répares", "répare", "réparons", "réparez", "réparent"),
      "réparé",
      Avoir,
    ),
    verb(
      "inviter",
      ["bjuda in"],
      "inviter",
      #("invite", "invites", "invite", "invitons", "invitez", "invitent"),
      "invité",
      Avoir,
    ),
    verb(
      "partager",
      ["dela"],
      "partager",
      #("partage", "partages", "partage", "partageons", "partagez", "partagent"),
      "partagé",
      Avoir,
    ),
    verb(
      "traduire",
      ["översätta"],
      "traduire",
      #(
        "traduis",
        "traduis",
        "traduit",
        "traduisons",
        "traduisez",
        "traduisent",
      ),
      "traduit",
      Avoir,
    ),
    verb(
      "etudier",
      ["studera", "plugga"],
      "étudier",
      #("étudie", "étudies", "étudie", "étudions", "étudiez", "étudient"),
      "étudié",
      Avoir,
    ),
    verb(
      "enseigner",
      ["undervisa"],
      "enseigner",
      #(
        "enseigne",
        "enseignes",
        "enseigne",
        "enseignons",
        "enseignez",
        "enseignent",
      ),
      "enseigné",
      Avoir,
    ),
    verb(
      "tourner",
      ["svänga"],
      "tourner",
      #("tourne", "tournes", "tourne", "tournons", "tournez", "tournent"),
      "tourné",
      Avoir,
    ),
    verb(
      "traverser",
      ["korsa", "gå över"],
      "traverser",
      #(
        "traverse",
        "traverses",
        "traverse",
        "traversons",
        "traversez",
        "traversent",
      ),
      "traversé",
      Avoir,
    ),
    verb(
      "discuter",
      ["diskutera"],
      "discuter",
      #("discute", "discutes", "discute", "discutons", "discutez", "discutent"),
      "discuté",
      Avoir,
    ),
    verb(
      "raconter",
      ["berätta"],
      "raconter",
      #("raconte", "racontes", "raconte", "racontons", "racontez", "racontent"),
      "raconté",
      Avoir,
    ),
    verb(
      "souhaiter",
      ["önska"],
      "souhaiter",
      #(
        "souhaite",
        "souhaites",
        "souhaite",
        "souhaitons",
        "souhaitez",
        "souhaitent",
      ),
      "souhaité",
      Avoir,
    ),
    verb(
      "sembler",
      ["verka"],
      "sembler",
      #("semble", "sembles", "semble", "semblons", "semblez", "semblent"),
      "semblé",
      Avoir,
    ),
    verb(
      "mourir",
      ["dö"],
      "mourir",
      #("meurs", "meurs", "meurt", "mourons", "mourez", "meurent"),
      "mort",
      Etre,
    ),
    verb(
      "grossir",
      ["gå upp i vikt"],
      "grossir",
      #(
        "grossis",
        "grossis",
        "grossit",
        "grossissons",
        "grossissez",
        "grossissent",
      ),
      "grossi",
      Avoir,
    ),
    verb(
      "maigrir",
      ["gå ner i vikt", "banta"],
      "maigrir",
      #(
        "maigris",
        "maigris",
        "maigrit",
        "maigrissons",
        "maigrissez",
        "maigrissent",
      ),
      "maigri",
      Avoir,
    ),
    verb(
      "guerir",
      ["bli frisk", "bota"],
      "guérir",
      #("guéris", "guéris", "guérit", "guérissons", "guérissez", "guérissent"),
      "guéri",
      Avoir,
    ),
    reflexive(
      "se-souvenir",
      ["komma ihåg", "minnas"],
      "souvenir",
      #(
        "souviens",
        "souviens",
        "souvient",
        "souvenons",
        "souvenez",
        "souviennent",
      ),
      "souvenu",
    ),
    reflexive(
      "se-marier",
      ["gifta sig"],
      "marier",
      #("marie", "maries", "marie", "marions", "mariez", "marient"),
      "marié",
    ),
    reflexive(
      "se-tromper",
      ["ta fel", "ha fel"],
      "tromper",
      #("trompe", "trompes", "trompe", "trompons", "trompez", "trompent"),
      "trompé",
    ),
    // Meningar
    sentence(
      "demain-je-vais-partir",
      "meningar",
      "I morgon ska jag åka.",
      "Demain, je ___ partir.",
      ["vais"],
      "aller",
    ),
    sentence(
      "hier-nous-sommes-alles",
      "meningar",
      "I går åkte vi till stranden.",
      "Hier, nous ___ allés à la plage.",
      ["sommes"],
      "être",
    ),
    sentence(
      "j-ai-mange-une-pomme",
      "meningar",
      "Jag åt ett äpple.",
      "J'___ mangé une pomme.",
      ["ai"],
      "avoir",
    ),
    sentence(
      "elle-est-partie-hier-soir",
      "meningar",
      "Hon åkte i går kväll.",
      "Elle est ___ hier soir.",
      ["partie"],
      "partir",
    ),
    sentence(
      "ils-sont-sortis",
      "meningar",
      "De gick ut ur huset.",
      "Ils sont ___ de la maison.",
      ["sortis"],
      "sortir",
    ),
    sentence(
      "ils-ont-regarde-un-film",
      "meningar",
      "De tittade på en film.",
      "Ils ont ___ un film.",
      ["regardé"],
      "regarder",
    ),
    sentence(
      "je-lisais-beaucoup",
      "meningar",
      "När jag var liten läste jag mycket.",
      "Quand j'étais petit, je ___ beaucoup.",
      ["lisais"],
      "lire",
    ),
    sentence(
      "il-faisait-beau-hier",
      "meningar",
      "Det var fint väder i går.",
      "Il ___ beau hier.",
      ["faisait"],
      "faire",
    ),
    sentence(
      "nous-etions-a-la-maison",
      "meningar",
      "Vi var hemma.",
      "Nous ___ à la maison.",
      ["étions"],
      "être, imparfait",
    ),
    sentence(
      "je-ne-sais-pas-ou",
      "meningar",
      "Jag vet inte var han är.",
      "Je ne ___ pas où il est.",
      ["sais"],
      "savoir",
    ),
    sentence(
      "nous-attendons-le-train",
      "meningar",
      "Vi väntar på tåget.",
      "Nous ___ le train.",
      ["attendons"],
      "attendre",
    ),
    sentence(
      "tu-dois-mettre-ton-manteau",
      "meningar",
      "Du måste ta på dig kappan.",
      "Tu ___ mettre ton manteau.",
      ["dois"],
      "devoir",
    ),
    sentence(
      "je-vais-voir-mes-amis",
      "meningar",
      "Jag ska träffa mina vänner i kväll.",
      "Je vais ___ mes amis ce soir.",
      ["voir"],
      "voir",
    ),
    sentence(
      "elle-travaille-au-bureau",
      "meningar",
      "Hon arbetar på kontoret.",
      "Elle ___ au bureau.",
      ["travaille"],
      "travailler",
    ),
    sentence(
      "j-achete-un-billet",
      "meningar",
      "Jag köper en biljett till Lyon.",
      "J'___ un billet pour Lyon.",
      ["achète"],
      "acheter",
    ),
    sentence(
      "on-part-a-quelle-heure",
      "meningar",
      "Vilken tid åker vi?",
      "On ___ à quelle heure ?",
      ["part"],
      "partir",
    ),
    sentence(
      "partitiv-sucre",
      "partitiv",
      "Det finns inget socker kvar.",
      "Il n'y a plus ___ sucre.",
      ["de"],
      "du/de la/des/de",
    ),
    sentence(
      "possessiv-maison",
      "possessiv",
      "De tycker om sitt hus.",
      "Ils aiment ___ maison.",
      ["leur"],
      "deras",
    ),
    sentence(
      "possessiv-parents",
      "possessiv",
      "Vi träffar våra föräldrar.",
      "Nous voyons ___ parents.",
      ["nos"],
      "våra",
    ),
    sentence(
      "possessiv-cle",
      "possessiv",
      "Var är hans nyckel?",
      "Où est ___ clé ?",
      ["sa"],
      "hans",
    ),
    sentence(
      "possessiv-billets",
      "possessiv",
      "Har ni era biljetter?",
      "Vous avez ___ billets ?",
      ["vos"],
      "era",
    ),
    sentence(
      "negation-jamais",
      "negation",
      "Jag äter aldrig kött.",
      "Je ne mange ___ de viande.",
      ["jamais"],
      "aldrig",
    ),
    sentence(
      "negation-plus",
      "negation",
      "Han bor inte här längre.",
      "Il n'habite ___ ici.",
      ["plus"],
      "inte längre",
    ),
    sentence(
      "negation-rien",
      "negation",
      "Vi ser ingenting.",
      "Nous ne voyons ___.",
      ["rien"],
      "ingenting",
    ),
    sentence(
      "negation-personne",
      "negation",
      "Hon känner ingen.",
      "Elle ne connaît ___.",
      ["personne"],
      "ingen",
    ),
    // Negation
    negate(
      "neg-je-suis-alle",
      "Jag gick inte på bio.",
      "Je suis allé au cinéma.",
      ["Je ne suis pas allé au cinéma."],
    ),
    negate("neg-elle-a-mange", "Hon har inte ätit.", "Elle a mangé.", [
      "Elle n'a pas mangé.",
    ]),
    negate("neg-je-vais-partir", "Jag ska inte åka.", "Je vais partir.", [
      "Je ne vais pas partir.",
    ]),
    negate("neg-il-se-leve", "Han går inte upp tidigt.", "Il se lève tôt.", [
      "Il ne se lève pas tôt.",
    ]),
    negate("neg-nous-avons", "Vi har inga barn.", "Nous avons des enfants.", [
      "Nous n'avons pas d'enfants.",
    ]),
    negate("neg-vous-voulez", "Vill ni inte ha te?", "Vous voulez du thé ?", [
      "Vous ne voulez pas de thé ?",
    ]),
    sentence(
      "pronomen-le",
      "pronomen",
      "Känner du Paul? Ja, jag känner honom.",
      "Tu connais Paul ? Oui, je ___ connais.",
      ["le"],
      "honom",
    ),
    sentence(
      "pronomen-y",
      "pronomen",
      "Ska du till marknaden? Ja, jag ska dit.",
      "Tu vas au marché ? Oui, j'___ vais.",
      ["y"],
      "dit",
    ),
    sentence(
      "pronomen-en",
      "pronomen",
      "Har du bröder? Ja, jag har två.",
      "Tu as des frères ? Oui, j'___ ai deux.",
      ["en"],
      "",
    ),
    sentence(
      "pronomen-lui",
      "pronomen",
      "Pratar du med din mamma? Ja, jag pratar med henne.",
      "Tu parles à ta mère ? Oui, je ___ parle.",
      ["lui"],
      "med henne",
    ),
    sentence(
      "pronomen-les",
      "pronomen",
      "Träffar ni era vänner? Ja, vi träffar dem.",
      "Vous voyez vos amis ? Oui, nous ___ voyons.",
      ["les"],
      "dem",
    ),
    sentence(
      "pronomen-leur",
      "pronomen",
      "Skriver du till dina föräldrar? Ja, jag skriver till dem.",
      "Tu écris à tes parents ? Oui, je ___ écris.",
      ["leur"],
      "till dem",
    ),
    sentence(
      "jamforelse-mieux-chante",
      "jämförelse",
      "Hon sjunger bättre än jag.",
      "Elle chante ___ que moi.",
      ["mieux"],
      "bien, mer",
    ),
    sentence(
      "jamforelse-mieux-parle",
      "jämförelse",
      "Han talar franska bättre än sin bror.",
      "Il parle français ___ que son frère.",
      ["mieux"],
      "bien, mer",
    ),
    sentence(
      "jamforelse-ville",
      "jämförelse",
      "Det är den vackraste staden i Frankrike.",
      "C'est la ville la ___ belle de France.",
      ["plus"],
      "mest",
    ),
    sentence(
      "jamforelse-film",
      "jämförelse",
      "Det är årets bästa film.",
      "C'est ___ film de l'année.",
      ["le meilleur"],
      "bon, mest",
    ),
    sentence(
      "jamforelse-que",
      "jämförelse",
      "Paris är större än Lyon.",
      "Paris est plus grand ___ Lyon.",
      ["que"],
      "",
    ),
    sentence(
      "jamforelse-aussi-que",
      "jämförelse",
      "Marie är lika lång som sin syster.",
      "Marie est aussi grande ___ sa sœur.",
      ["que"],
      "",
    ),
    sentence(
      "futur-il-fera-beau",
      "futur",
      "I morgon blir det fint väder.",
      "Demain, il ___ beau.",
      ["fera"],
      "faire",
    ),
    sentence(
      "futur-nous-irons",
      "futur",
      "Nästa år åker vi till Frankrike.",
      "L'année prochaine, nous ___ en France.",
      ["irons"],
      "aller",
    ),
    sentence(
      "futur-je-t-appellerai",
      "futur",
      "Jag ringer dig i morgon.",
      "Je t'___ demain.",
      ["appellerai"],
      "appeler",
    ),
    sentence(
      "futur-tu-seras",
      "futur",
      "När du blir stor kommer du att förstå.",
      "Quand tu ___ grand, tu comprendras.",
      ["seras"],
      "être",
    ),
    sentence(
      "konditionalis-cafe",
      "konditionalis",
      "Jag skulle vilja ha en kaffe, tack.",
      "Je ___ un café, s'il vous plaît.",
      ["voudrais"],
      "vouloir",
    ),
    sentence(
      "konditionalis-pourriez",
      "konditionalis",
      "Skulle ni kunna hjälpa mig?",
      "Vous ___ m'aider ?",
      ["pourriez"],
      "pouvoir",
    ),
    sentence(
      "konditionalis-pourrais",
      "konditionalis",
      "Skulle du kunna följa med oss?",
      "Tu ___ venir avec nous ?",
      ["pourrais"],
      "pouvoir",
    ),
    sentence(
      "konditionalis-si-argent",
      "konditionalis",
      "Om jag hade pengar skulle jag köpa ett hus.",
      "Si j'avais de l'argent, j'___ une maison.",
      ["achèterais"],
      "acheter",
    ),
    sentence(
      "konditionalis-a-ta-place",
      "konditionalis",
      "I ditt ställe skulle jag ta tåget.",
      "À ta place, je ___ le train.",
      ["prendrais"],
      "prendre",
    ),
    // Pronomen
    pronoun("pron-je-vois-marie", "Jag ser henne.", "Je vois [Marie].", [
      "Je la vois.",
    ]),
    pronoun("pron-il-mange-gateau", "Han äter den.", "Il mange [le gâteau].", [
      "Il le mange.",
    ]),
    pronoun(
      "pron-nous-regardons-photos",
      "Vi tittar på dem.",
      "Nous regardons [les photos].",
      ["Nous les regardons."],
    ),
    pronoun("pron-tu-aimes-film", "Tycker du om den?", "Tu aimes [ce film] ?", [
      "Tu l'aimes ?",
    ]),
    pronoun(
      "pron-j-attends-train",
      "Jag väntar på det.",
      "J'attends [le train].",
      ["Je l'attends."],
    ),
    pronoun(
      "pron-elle-cherche-cles",
      "Hon letar efter dem.",
      "Elle cherche [ses clés].",
      ["Elle les cherche."],
    ),
    pronoun(
      "pron-je-parle-paul",
      "Jag pratar med honom.",
      "Je parle [à Paul].",
      ["Je lui parle."],
    ),
    pronoun(
      "pron-elle-telephone-mere",
      "Hon ringer till henne.",
      "Elle téléphone [à sa mère].",
      ["Elle lui téléphone."],
    ),
    pronoun(
      "pron-nous-donnons-amis",
      "Vi ger dem en present.",
      "Nous donnons un cadeau [à nos amis].",
      ["Nous leur donnons un cadeau."],
    ),
    pronoun(
      "pron-tu-reponds-professeur",
      "Svarar du honom?",
      "Tu réponds [au professeur] ?",
      ["Tu lui réponds ?"],
    ),
    pronoun("pron-je-vais-paris", "Jag åker dit.", "Je vais [à Paris].", [
      "J'y vais.",
    ]),
    pronoun(
      "pron-elle-habite-france",
      "Hon bor där.",
      "Elle habite [en France].",
      ["Elle y habite."],
    ),
    pronoun(
      "pron-je-mange-soupe",
      "Jag äter lite av den.",
      "Je mange [de la soupe].",
      ["J'en mange."],
    ),
    pronoun("pron-il-a-enfants", "Han har tre.", "Il a [trois enfants].", [
      "Il en a trois.",
    ]),
    pronoun(
      "pron-nous-voulons-cafe",
      "Vi vill ha lite.",
      "Nous voulons [du café].",
      ["Nous en voulons."],
    ),
    pronoun(
      "pron-je-ne-vois-pas-marie",
      "Jag ser henne inte.",
      "Je ne vois pas [Marie].",
      ["Je ne la vois pas."],
    ),
    pronoun("pron-j-ai-vu-film", "Jag har sett den.", "J'ai vu [le film].", [
      "Je l'ai vu.",
    ]),
    pronoun(
      "pron-je-vais-acheter-pain",
      "Jag ska köpa det.",
      "Je vais acheter [le pain].",
      ["Je vais l'acheter."],
    ),
    // Texter
    text(
      "text-vacances-nice",
      "Les vacances à Nice",
      "L'été dernier, nous sommes allés à Nice en train. Le voyage a duré six heures.\nNous avons loué un petit appartement près de la mer. Tous les jours, nous sommes allés à la plage et nous avons nagé.\nUn soir, nous avons mangé du poisson dans un restaurant sur le port. C'était délicieux !\nMalheureusement, il a plu le dernier jour.",
      "I somras åkte vi till Nice med tåg. Resan tog sex timmar.\nVi hyrde en liten lägenhet nära havet. Varje dag gick vi till stranden och badade.\nEn kväll åt vi fisk på en restaurang i hamnen. Det var jättegott!\nTyvärr regnade det den sista dagen.",
      [
        question(
          "Hur reste de till Nice?",
          ["Med flyg", "Med tåg", "Med bil"],
          1,
        ),
        question(
          "Hur lång tid tog resan?",
          ["Sex timmar", "Fyra timmar", "Åtta timmar"],
          0,
        ),
        question(
          "Var bodde de?",
          [
            "På ett stort hotell i stan",
            "Hemma hos några vänner",
            "I en liten lägenhet nära havet",
          ],
          2,
        ),
        question(
          "Hur var vädret den sista dagen?",
          ["Soligt", "Det regnade", "Det snöade"],
          1,
        ),
      ],
    ),
    text(
      "text-message-paul",
      "Un message de Paul",
      "Salut Sophie !\nSamedi prochain, je ferai une fête chez moi pour mon anniversaire. Il y aura beaucoup d'amis et nous mangerons une pizza.\nMon frère viendra avec sa guitare. Tu pourras venir ? La fête commencera à huit heures.\nRéponds-moi vite ! À bientôt, Paul",
      "Hej Sophie!\nNästa lördag ska jag ha fest hemma hos mig för att jag fyller år. Det kommer många vänner och vi ska äta pizza.\nMin bror kommer med sin gitarr. Kan du komma? Festen börjar klockan åtta.\nSvara snabbt! Vi ses snart, Paul",
      [
        question(
          "Varför har Paul fest?",
          ["Han fyller år", "Han har fått ett nytt jobb", "Han har flyttat"],
          0,
        ),
        question(
          "Vem tar med sig en gitarr?",
          ["Sophie", "Pauls syster", "Pauls bror"],
          2,
        ),
        question(
          "När börjar festen?",
          ["Klockan sju", "Klockan åtta", "Klockan nio"],
          1,
        ),
      ],
    ),
    text(
      "text-medecin",
      "Chez le médecin",
      "— Bonjour, docteur.\n— Bonjour, madame. Qu'est-ce qui ne va pas ?\n— J'ai mal à la tête et j'ai de la fièvre depuis deux jours.\n— Vous toussez ?\n— Oui, un peu.\n— C'est la grippe. Restez à la maison et reposez-vous. Prenez ce médicament trois fois par jour.\n— Merci, docteur.",
      "– Hej, doktorn.\n– Hej. Vad är det som är fel?\n– Jag har ont i huvudet och har haft feber i två dagar.\n– Hostar ni?\n– Ja, lite.\n– Det är influensa. Stanna hemma och vila. Ta den här medicinen tre gånger om dagen.\n– Tack, doktorn.",
      [
        question(
          "Hur länge har kvinnan haft feber?",
          ["Två dagar", "En dag", "En vecka"],
          0,
        ),
        question(
          "Vad säger läkaren att hon har?",
          ["En förkylning", "Huvudvärk", "Influensa"],
          2,
        ),
        question(
          "Hur ofta ska hon ta medicinen?",
          ["En gång om dagen", "Tre gånger om dagen", "Två gånger om dagen"],
          1,
        ),
      ],
    ),
    text(
      "text-quand-j-etais-petit",
      "Quand j'étais petit",
      "Quand j'étais petit, j'habitais dans un village à la campagne.\nNotre maison était vieille mais très grande. Il y avait un grand jardin avec des arbres et des fleurs.\nTous les matins, j'allais à l'école à pied avec mon voisin.\nLe mercredi, nous jouions au football dans le champ derrière l'église. J'étais très heureux.",
      "När jag var liten bodde jag i en by på landet.\nVårt hus var gammalt men väldigt stort. Det fanns en stor trädgård med träd och blommor.\nVarje morgon gick jag till skolan med min granne.\nPå onsdagarna spelade vi fotboll på fältet bakom kyrkan. Jag var väldigt lycklig.",
      [
        question(
          "Var bodde personen som barn?",
          ["I en by på landet", "I en stor stad", "Vid havet"],
          0,
        ),
        question(
          "Hur var huset?",
          [
            "Litet och helt nytt",
            "Modernt med en pool",
            "Gammalt men väldigt stort",
          ],
          2,
        ),
        question(
          "Vad gjorde de på onsdagarna?",
          ["De badade", "De spelade fotboll", "De läste"],
          1,
        ),
      ],
    ),
    text(
      "text-nouvel-appartement",
      "Un nouvel appartement",
      "Le mois dernier, j'ai trouvé un nouvel appartement au centre-ville.\nIl est plus petit que mon ancien appartement, mais il est moins cher.\nIl y a un salon, une chambre, une cuisine et une salle de bain. La cuisine est moderne et le salon a deux grandes fenêtres.\nLe seul problème : il n'y a pas d'ascenseur et j'habite au cinquième étage !",
      "Förra månaden hittade jag en ny lägenhet i centrum.\nDen är mindre än min gamla lägenhet, men den är billigare.\nDet finns ett vardagsrum, ett sovrum, ett kök och ett badrum. Köket är modernt och vardagsrummet har två stora fönster.\nDet enda problemet: det finns ingen hiss och jag bor på femte våningen!",
      [
        question(
          "Var ligger den nya lägenheten?",
          ["I centrum", "På landet", "Nära flygplatsen"],
          0,
        ),
        question(
          "Hur är den jämfört med den gamla?",
          ["Större och dyrare", "Lika stor", "Mindre men billigare"],
          2,
        ),
        question(
          "Vad är problemet?",
          ["Köket är gammalt", "Det finns ingen hiss", "Den är för dyr"],
          1,
        ),
      ],
    ),
    text(
      "text-au-travail",
      "Au travail",
      "Je m'appelle Karim et je suis cuisinier dans un restaurant à Paris.\nJe commence à travailler à dix heures et je finis tard le soir.\nLe travail est difficile mais j'aime beaucoup mon métier. Mes collègues sont très sympathiques.\nL'année prochaine, je voudrais ouvrir mon propre restaurant.",
      "Jag heter Karim och är kock på en restaurang i Paris.\nJag börjar jobba klockan tio och slutar sent på kvällen.\nJobbet är tungt men jag tycker mycket om mitt yrke. Mina kollegor är väldigt trevliga.\nNästa år skulle jag vilja öppna en egen restaurang.",
      [
        question(
          "Vad arbetar Karim med?",
          ["Han är kock", "Han är servitör", "Han är bagare"],
          0,
        ),
        question(
          "När börjar han jobba?",
          ["Klockan åtta", "Klockan tolv", "Klockan tio"],
          2,
        ),
        question(
          "Vad vill han göra nästa år?",
          ["Flytta till Lyon", "Öppna en egen restaurang", "Sluta jobba"],
          1,
        ),
      ],
    ),
    // Fler texter
    text(
      "text-premier-jour",
      "Mon premier jour de travail",
      "Lundi dernier, j'ai commencé un nouveau travail dans une entreprise à Lille.\nJe me suis levé à six heures parce que j'étais nerveux. Je suis arrivé au bureau à huit heures.\nMa patronne m'a présenté mes collègues et elle m'a montré mon ordinateur.\nÀ midi, nous avons déjeuné ensemble dans un petit restaurant. Le soir, j'étais fatigué mais content.",
      "I måndags började jag ett nytt jobb på ett företag i Lille.\nJag gick upp klockan sex eftersom jag var nervös. Jag kom till kontoret klockan åtta.\nMin chef presenterade mina kollegor och visade mig min dator.\nVid lunch åt vi tillsammans på en liten restaurang. På kvällen var jag trött men nöjd.",
      [
        question(
          "I vilken stad ligger företaget?",
          ["I Lille", "I Lyon", "I Nantes"],
          0,
        ),
        question(
          "Varför gick han upp klockan sex?",
          ["Han hade långt till jobbet", "Han skulle träna", "Han var nervös"],
          2,
        ),
        question(
          "Var åt de lunch?",
          ["På kontoret", "På en liten restaurang", "Hemma"],
          1,
        ),
        question(
          "Hur kände han sig på kvällen?",
          ["Trött men nöjd", "Ledsen", "Arg"],
          0,
        ),
      ],
    ),
    text(
      "text-week-end-paris",
      "Un week-end à Paris",
      "Le week-end dernier, Sarah et Tom sont partis à Paris.\nLe samedi, ils ont visité le musée du Louvre et ils ont vu la Joconde. Il y avait beaucoup de touristes !\nLe soir, ils ont dîné dans un restaurant près de la Seine.\nLe dimanche, il a plu, alors ils sont restés à l'hôtel et ils ont lu. Ils sont rentrés en train dimanche soir.",
      "Förra helgen åkte Sarah och Tom till Paris.\nPå lördagen besökte de Louvren och såg Mona Lisa. Det var massor av turister!\nPå kvällen åt de middag på en restaurang nära Seine.\nPå söndagen regnade det, så de stannade på hotellet och läste. De åkte hem med tåg på söndagskvällen.",
      [
        question(
          "Vilket museum besökte de?",
          ["Orsaymuseet", "Pompidoucentret", "Louvren"],
          2,
        ),
        question(
          "Varför stannade de på hotellet på söndagen?",
          ["De var trötta", "Det regnade", "Museet var stängt"],
          1,
        ),
        question("Hur åkte de hem?", ["Med tåg", "Med flyg", "Med bil"], 0),
      ],
    ),
    text(
      "text-au-telephone",
      "Au téléphone",
      "— Allô, Julie ? C'est Marc.\n— Salut Marc ! Ça va ?\n— Oui, très bien. Tu es libre ce soir ? Je vais aller au cinéma avec Paul.\n— Ce soir, je ne peux pas. Je vais dîner chez mes parents.\n— Dommage ! Et demain ?\n— Demain, oui ! On se retrouve devant le cinéma à sept heures ?\n— D'accord. À demain !",
      "– Hallå, Julie? Det är Marc.\n– Hej Marc! Hur är det?\n– Bara bra. Är du ledig i kväll? Jag ska gå på bio med Paul.\n– I kväll kan jag inte. Jag ska äta middag hos mina föräldrar.\n– Synd! Och i morgon?\n– I morgon, ja! Ses vi utanför bion klockan sju?\n– Okej. Vi ses i morgon!",
      [
        question(
          "Varför ringer Marc?",
          [
            "För att fråga om vägen",
            "För att boka ett bord",
            "För att bjuda med Julie på bio",
          ],
          2,
        ),
        question(
          "Vad ska Julie göra i kväll?",
          ["Jobba", "Äta middag hos sina föräldrar", "Träffa Paul"],
          1,
        ),
        question(
          "När och var ska de ses?",
          [
            "I morgon klockan sju utanför bion",
            "I kväll klockan åtta hos Paul",
            "På lördag klockan tre på kaféet",
          ],
          0,
        ),
      ],
    ),
    text(
      "text-ville-campagne",
      "La ville et la campagne",
      "Avant, j'habitais à Paris. La vie en ville était plus rapide et plus chère.\nIl y avait plus de restaurants et de magasins, mais aussi plus de bruit.\nMaintenant, j'habite à la campagne. Ma maison est plus grande et moins chère que mon appartement à Paris.\nJe suis plus calme, mais je vois moins souvent mes amis.",
      "Förut bodde jag i Paris. Livet i stan var snabbare och dyrare.\nDet fanns fler restauranger och affärer, men också mer buller.\nNu bor jag på landet. Mitt hus är större och billigare än min lägenhet i Paris.\nJag är lugnare, men jag träffar mina vänner mer sällan.",
      [
        question(
          "Hur var livet i stan?",
          ["Lugnare", "Billigare", "Snabbare och dyrare"],
          2,
        ),
        question(
          "Hur är huset jämfört med lägenheten?",
          ["Mindre och dyrare", "Större och billigare", "Lika stort"],
          1,
        ),
        question(
          "Vad är nackdelen med att bo på landet?",
          [
            "Personen träffar sina vänner mer sällan",
            "Det är mycket buller på nätterna",
            "Huset är kallt på vintern",
          ],
          0,
        ),
      ],
    ),
    text(
      "text-projets-lea",
      "Les projets de Léa",
      "L'année prochaine, Léa finira ses études. Elle voudrait travailler à l'étranger.\nD'abord, elle passera six mois en Espagne pour apprendre l'espagnol.\nEnsuite, elle cherchera un travail à Madrid ou à Barcelone.\nSes parents seront tristes, mais ils viendront la voir en été.",
      "Nästa år blir Léa klar med sina studier. Hon skulle vilja arbeta utomlands.\nFörst ska hon tillbringa sex månader i Spanien för att lära sig spanska.\nSedan ska hon söka jobb i Madrid eller Barcelona.\nHennes föräldrar kommer att bli ledsna, men de kommer att hälsa på henne på sommaren.",
      [
        question(
          "Vad händer nästa år?",
          [
            "Léa börjar på universitetet",
            "Léa flyttar hem till sina föräldrar",
            "Léa blir klar med sina studier",
          ],
          2,
        ),
        question(
          "Varför åker hon först till Spanien?",
          ["För att jobba", "För att lära sig spanska", "För att träffa vänner"],
          1,
        ),
        question(
          "När ska föräldrarna hälsa på?",
          ["På sommaren", "På julen", "På våren"],
          0,
        ),
      ],
    ),
    text(
      "text-souvenir-enfance",
      "Un souvenir d'enfance",
      "Quand j'avais dix ans, nous passions toutes les vacances chez mes grands-parents en Bretagne.\nIl faisait souvent gris, mais nous allions à la plage tous les jours.\nUn jour, mon frère est tombé dans l'eau avec ses vêtements ! Tout le monde a ri.\nLe soir, ma grand-mère préparait des crêpes.",
      "När jag var tio år tillbringade vi alla lov hos mina far- och morföräldrar i Bretagne.\nDet var ofta mulet, men vi gick till stranden varje dag.\nEn dag ramlade min bror i vattnet med kläderna på! Alla skrattade.\nPå kvällarna gjorde min mormor pannkakor.",
      [
        question(
          "Var tillbringade de loven?",
          [
            "Hos en kusin i Paris",
            "På ett hotell i Spanien",
            "Hos far- och morföräldrarna i Bretagne",
          ],
          2,
        ),
        question(
          "Vad hände en dag?",
          [
            "De gick vilse i skogen en kväll",
            "Brodern ramlade i vattnet med kläderna på",
            "En storm förstörde deras tält",
          ],
          1,
        ),
        question(
          "Vad gjorde mormodern på kvällarna?",
          ["Pannkakor", "Soppa", "Fisk"],
          0,
        ),
      ],
    ),
    text(
      "text-a-l-hotel",
      "À l'hôtel",
      "— Bonjour, je voudrais une chambre pour deux nuits, s'il vous plaît.\n— Bien sûr. Pour combien de personnes ?\n— Pour une personne. Est-ce que la chambre a une vue sur la mer ?\n— Oui, elle est au quatrième étage. Le petit-déjeuner est compris.\n— Parfait. Est-ce que je pourrais payer par carte ?\n— Oui, sans problème. Voici votre clé.",
      "– Hej, jag skulle vilja ha ett rum för två nätter, tack.\n– Självklart. För hur många personer?\n– För en person. Har rummet utsikt över havet?\n– Ja, det ligger på fjärde våningen. Frukost ingår.\n– Perfekt. Skulle jag kunna betala med kort?\n– Ja, inga problem. Här är er nyckel.",
      [
        question(
          "Hur många nätter vill gästen stanna?",
          ["En", "Tre", "Två"],
          2,
        ),
        question("Vad ser man från rummet?", ["Bergen", "Havet", "En park"], 1),
        question("Vad ingår i priset?", ["Frukost", "Middag", "Parkering"], 0),
      ],
    ),
  ]
}

fn entry(id: String, theme: String, sv: List(String), word: Word) -> Entry {
  Entry(id:, level: A2, theme:, sv:, word:)
}

fn phrase(id, theme, sv, fr) -> Entry {
  entry(id, theme, sv, Expression(fr))
}

fn noun(id, theme, fr, gender, sv) -> Entry {
  entry(id, theme, sv, lexicon.noun(fr, gender))
}

/// `forms` are the présent forms; `participle` and `auxiliary` give the
/// passé composé.
fn verb(id, sv, infinitive, forms, participle, auxiliary) -> Entry {
  let #(je, tu, il, nous, vous, ils) = forms
  entry(
    id,
    "verb",
    sv,
    Verb(
      infinitive:,
      present: Present(je:, tu:, il:, nous:, vous:, ils:),
      participle:,
      auxiliary:,
      reflexive: False,
    ),
  )
}

/// A sentence with a `___` gap, its Swedish translation, the accepted
/// answers for the gap and a hint ("" for none).
fn sentence(id, theme, sv, text, answers, hint) -> Entry {
  entry(id, theme, [sv], Sentence(text:, answers:, hint:))
}

fn adjective(id, theme, sv, masculine, feminine) -> Entry {
  entry(id, theme, sv, lexicon.adjective(masculine, feminine))
}

/// A reflexive verb, given without its pronoun ("lever" for se lever). It
/// takes être in the passé composé.
fn reflexive(id, sv, infinitive, forms, participle) -> Entry {
  let #(je, tu, il, nous, vous, ils) = forms
  entry(
    id,
    "verb",
    sv,
    Verb(
      infinitive:,
      present: Present(je:, tu:, il:, nous:, vous:, ils:),
      participle:,
      auxiliary: Etre,
      reflexive: True,
    ),
  )
}

/// A sentence to make negative, the Swedish meaning of the negative one and
/// the accepted negative sentences.
fn negate(id, sv, source, answers) -> Entry {
  entry(id, "negation", [sv], Rewrite(task: Negate, source:, answers:))
}

/// A sentence whose [marked] part is to be replaced by a pronoun, the
/// Swedish meaning of the answer and the accepted answers.
fn pronoun(id, sv, source, answers) -> Entry {
  entry(id, "pronomen", [sv], Rewrite(task: UsePronoun, source:, answers:))
}

/// A text with its Swedish translation and comprehension questions.
fn text(id, title, french, swedish, questions) -> Entry {
  entry(id, "texter", [title], Text(title:, french:, swedish:, questions:))
}

fn question(question, options, answer) -> Question {
  Question(question:, options:, answer:)
}
